kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: quay.io/infinispan-test/kindest-node:v1.17.17
    extraPortMappings:
      - containerPort: 30222
        hostPort: 11222
