[id='backups-automatic-offline_{context}']
= Performance considerations with taking backup locations offline
Backup locations can automatically go offline when remote sites become
unavailable. This prevents nodes from attempting to replicate data to offline
backup locations, which can have a performance impact on your cluster because it
results in error.

You can configure how long to wait before backup locations go offline. A good
rule of thumb is one or two minutes. However, you should test different wait
periods and evaluate their performance impacts to determine the correct value
for your deployment.

For instance when {openshiftshort} terminates the site master pod, that backup
location becomes unavailable for a short period of time until {ispn_operator}
elects a new site master. In this case, if the minimum wait time is not long
enough then the backup locations go offline. You then need to bring those
backup locations online and perform state transfer operations to ensure the
data is in sync.

Likewise, if the minimum wait time is too long, node CPU usage increases from
failed backup attempts which can lead to performance degradation.
