[id='services_{context}']
= Service types

[role="_abstract"]
Services are stateful applications, based on the {brandname} Server image, that provide flexible and robust in-memory data storage.

== {datagridservice}

Deploy clusters of {datagridservice} pods if you want to:

* Back up data across global clusters with cross-site replication.
* Create caches with any valid configuration.
* Add file-based cache stores to save data in a persistent volume.
* Query values across caches using the {brandname} Query API.
* Use advanced {brandname} features and capabilities.

== {cacheservice}

Deploy clusters of {cacheservice} pods if you want a low-latency data store with minimal configuration.

{cacheservice} pods provide volatile storage only, which means you lose all data when you modify your `Infinispan` CR or update the version of your {brandname} cluster.
However, if you only want to quickly provide applications with high-performance caching without the overhead of configuration then you can use {cacheservice} pods to:

* Automatically scale to meet capacity when data storage demands go up or down.
* Synchronously distribute data to ensure consistency.
* Replicates each entry in the cache across the cluster.
* Store cache entries off-heap and use eviction for JVM efficiency.
* Ensure data consistency with a default partition handling configuration.

[IMPORTANT]
====
//Community content
ifdef::community[]
The {brandname} team recommend that you deploy {datagridservice} pods instead of {cacheservice} pods.
endif::community[]
//Downstream content
ifdef::downstream[]
Red Hat recommends that you deploy {datagridservice} pods instead of {cacheservice} pods.
endif::downstream[]

{cacheservice} is planned for removal in the next version of the `Infinispan` CRD.
{datagridservice} remains under active development and will continue to benefit from new features and improved tooling to automate complex operations such as upgrading clusters and migrating data.
====
