[id='cluster-upgrades_{context}']
= {brandname} cluster upgrades

[role="_abstract"]
The `spec.upgrades.type` field controls how {ispn_operator} upgrades your {brandname} cluster when new versions become available.
There are three types of cluster upgrade:

`Shutdown`:: Upgrades {brandname} clusters, with service downtime, by bringing down the original cluster and bringing up a new one in its place. This is the default upgrade type.
`InPlaceRolling`:: Upgrades {brandname} cluster pods to new patch releases individually, using a StatefulSet RollingUpdate.
`HotRodRolling`:: Upgrades {brandname} versions, without service downtime, by deploying a new cluster in parallel to the original and transitioning all traffic to it.
+
[IMPORTANT]
====
The Operator does not automatically upgrade clusters to a new {brandname} server version. In order to trigger an upgrade, you must explicitly change the `spec.version` element to a new version.
====

[discrete]
== Shutdown upgrades

To perform a shutdown upgrade, {ispn_operator} does the following:

. Gracefully shuts down the existing cluster.
. Removes the existing cluster.
. Creates a new cluster with the target version.

[discrete]
== InPlaceRolling upgrades

To perform a rolling upgrade, {ispn_operator} does the following:

. Checks if the {brandname} version supports rolling upgrades.
. Checks whether the current version and target version have matching major and minor versions.
. If the conditions above are met, the Operator will upgrade server pods one by one using a StatefulSet RollingUpdate.

[IMPORTANT]
===
When upgrading between different major or minor versions of the server, the "Shutdown" or "HotRodRolling" upgrade type is required. This must be configured in the CR spec at the the same time as the new version.
===

[discrete]
== HotRodRolling upgrades

To perform a Hot Rod rolling upgrade, {ispn_operator} does the following:

. Creates a new {brandname} cluster with the target version that runs alongside your existing cluster.
. Creates a remote cache store to transfer data from the existing cluster to the new cluster.
. Redirects all clients to the new cluster.
. Removes the existing cluster when all data and client connections are transferred to the new cluster.

[IMPORTANT]
====
You should not perform Hot Rod rolling upgrades with caches that enable passivation with persistent cache stores.
In the event that the upgrade does not complete successfully, passivation can result in data loss when {ispn_operator} rolls back the target cluster.

If your cache configuration enables passivation you should perform a shutdown upgrade.
====
