[id='automatic-scaling_{context}']
= Automatic scaling

[role="_abstract"]
{ispn_operator} can monitor the default cache on {cacheservice} pods to automatically scale clusters up or down, by creating or deleting pods based on memory usage.

[IMPORTANT]
====
Automatic scaling is available for clusters of {cacheservice} pods only.
{ispn_operator} does not perform automatic scaling for clusters of {datagridservice} pods.
====

When you enable automatic scaling, you define memory usage thresholds that let {ispn_operator} determine when it needs to create or delete pods.
{ispn_operator} monitors statistics for the default cache and, when memory usage reaches the configured thresholds, scales your clusters up or down.

.Maximum threshold

This threshold sets an upper boundary for the amount of memory that pods in your cluster can use before scaling up or performing eviction.
When {ispn_operator} detects that any node reaches the maximum amount of memory that you configure, it creates a new node if possible.
If {ispn_operator} cannot create a new node then it performs eviction when memory usage reaches 100 percent.

.Minimum threshold

This threshold sets a lower boundary for memory usage across your {brandname} cluster.
When {ispn_operator} detects that memory usage falls below the minimum, it shuts down pods.

.Default cache only

Autoscaling capabilities work with the default cache only.
If you plan to add other caches to your cluster, you should not include the `autoscale` field in your `Infinispan` CR.
In this case you should use eviction to control the size of the data container on each node.
