[id='backup-restore_{context}']
= Backup and Restore CRs

[role="_abstract"]
`Backup` and `Restore` CRs save in-memory data at runtime so you can easily recreate {brandname} clusters.

Applying a `Backup` or `Restore` CR creates a new pod that joins the {brandname} cluster as a zero-capacity member, which means it does not require cluster rebalancing or state transfer to join.

For backup operations, the pod iterates over cache entries and other resources and creates an archive, a `.zip` file, in the `{backup_path}` directory on the persistent volume (PV).

[NOTE]
====
Performing backups does not significantly impact performance because the other nodes in the {brandname} cluster only need to respond to the backup pod as it iterates over cache entries.
====

For restore operations, the pod retrieves {brandname} resources from the archive on the PV and applies them to the {brandname} cluster.

When either the backup or restore operation completes, the pod leaves the cluster and is terminated.

.Reconciliation

{ispn_operator} does not reconcile `Backup` and `Restore` CRs which mean that backup and restore operations are "one-time" events.

Modifying an existing `Backup` or `Restore` CR instance does not perform an operation or have any effect.
If you want to update `.spec` fields, you must create a new instance of the `Backup` or `Restore` CR.
