[id='cross-site-replication_{context}']
= Using {ispn_operator} to manage cross-site connections

[role="_abstract"]
{ispn_operator} in one data center can discover a {brandname} cluster that {ispn_operator} manages in another data center.
This discovery allows {brandname} to automatically form cross-site views and create global clusters.

The following illustration provides an example in which {ispn_operator} manages a {brandname} cluster at a data center in New York City, **NYC**.
At another data center in London, **LON**, {ispn_operator} also manages a {brandname} cluster.

ifdef::community[]
image::xsite-ispn.svg[]
endif::community[]

ifdef::downstream[]
image::xsite-rhdg.svg[]
endif::downstream[]

{ispn_operator} uses the Kubernetes API to establish a secure connection between the {ocp} clusters in **NYC** and **LON**.
{ispn_operator} then creates a cross-site replication service so {brandname} clusters can back up data across locations.

[IMPORTANT]
====
{ispn_operator} in each {openshiftshort} cluster must have network access to the remote Kubernetes API.
====

[NOTE]
====
When you configure automatic connections, {brandname} clusters do not start running until {ispn_operator} discovers all backup locations in the configuration.
====

Each {brandname} cluster has one site master node that coordinates all backup requests.
{ispn_operator} identifies the site master node so that all traffic through the cross-site replication service goes to the site master.

If the current site master node goes offline then a new node becomes site master.
{ispn_operator} automatically finds the new site master node and updates the cross-site replication service to forward backup requests to it.
