[id='cache-cr_{context}']
= Cache CRs

[role="_abstract"]
Find out details for configuring {brandname} caches with `Cache` CR.

When using `Cache` CRs, the following rules apply:

* `Cache` CRs apply to {datagridservice} nodes only.
* You can create a single cache for each `Cache` CR.
* If your `Cache` CR contains both a template and an XML configuration, {ispn_operator} uses the template.
* If you edit caches in the {osweb}, the changes are reflected through the user interface but do not take effect on the {brandname} cluster. You cannot edit caches. To change cache configuration, you must first delete the cache through the console or CLI and then re-create the cache.
* Deleting `Cache` CRs in the {osweb} does not remove caches from {brandname} clusters. You must delete caches through the console or CLI.

[NOTE]
====
In previous versions, you need to add credentials to a secret so that {ispn_operator} can access your cluster when creating caches.

That is no longer necessary.
{ispn_operator} uses the **operator** user and corresponding password to perform cache operations.
====
