[id='client-connection-details_{context}']
= Client connection details

[role="_abstract"]
Client connections to {brandname} require the following information:

* Hostname
* Port
* Authentication credentials, if required
* TLS certificate, if you use encryption

.Hostnames

The hostname you use depends on whether client connections are on the same {k8s} cluster as {brandname}.

Client applications running on the same {k8s} cluster use the internal service name for the {brandname} cluster.

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/metadata_name.yaml[]
----

Client applications running outside {k8s} use one of the following as the host name:

A `LoadBalancer` service uses the URL for the load balancer.
A `NodePort` service uses the node host name.
An {openshift} `Route` uses either a custom hostname or a system-defined hostname.

.Ports

Client connections on {k8s} and a through `LoadBalancer` service use port `11222`.

`NodePort` services use a port in the range of `30000` to `60000`.
Routes use either port `80` (unencrypted) or `443` (encrypted).

[role="_additional-resources"]
.Additional resources
* link:#creating-network[Configuring Network Access to {brandname}]
* link:#retrieving-credentials_authn[Retrieving Credentials]
* link:#retrieving-tls-certificates_tls[Retrieving TLS Certificates]
