[id='managed-cross-site-connections_{context}']
= Managed cross-site replication

[role="_abstract"]
{ispn_operator} can discover {brandname} clusters running in different data centers to form global clusters.

When you configure managed cross-site connections, {ispn_operator} creates router pods in each {brandname} cluster.
{brandname} pods use the `<cluster_name>-site` service to connect to these router pods and send backup requests.

Router pods maintain a record of all pod IP addresses and parse RELAY message headers to forward backup requests to the correct {brandname} cluster.
If a router pod crashes then all {brandname} pods start using any other available router pod until {k8s} restores it.

[IMPORTANT]
====
To manage cross-site connections, {ispn_operator} uses the Kubernetes API.
Each {openshiftshort} cluster must have network access to the remote Kubernetes API and a service account token for each backup cluster.
====

[NOTE]
====
{brandname} clusters do not start running until {ispn_operator} discovers all backup locations that you configure.
====
