[id='creating-service-monitor_{context}']
= Creating a Prometheus service monitor

[role="_abstract"]
{ispn_operator} automatically creates a Prometheus `ServiceMonitor` that scrapes metrics from your {brandname} cluster.

.Procedure

Enable monitoring for user-defined projects on {ocp}.

When the Operator detects an `Infinispan` CR with the monitoring annotation set to `true`, which is the default, {ispn_operator} does the following:

* Creates a `ServiceMonitor` named `<cluster_name>-monitor`.
* If the annotation wasn't explicitly set to true, adds `infinispan.org/monitoring: 'true'` annotation to your `Infinispan` CR  metatada:

+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/infinispan-monitoring-true.yaml[]
----

[NOTE]
====
To authenticate with {brandname}, Prometheus uses the `operator` credentials.
====

.Verification

You can check that Prometheus is scraping {brandname} metrics as follows:

. In the {osweb}, select the **</> Developer** perspective and then select **Monitoring**.
. Open the **Dashboard** tab for the namespace where your {brandname} cluster runs.
. Open the **Metrics** tab and confirm that you can query {brandname} metrics such as:
+
----
vendor_cache_manager_default_cluster_size
----

[role="_additional-resources"]
.Additional resources
* link:{link_os_monitoring}
