[id='exposing-routes_{context}']
= Exposing {brandname} through routes
//Community
ifdef::community[]
Use a {k8s} Ingress or an {openshiftshort} Route with passthrough encryption to
make {brandname} clusters available on the network.
endif::community[]
//Downstream
ifdef::downstream[]
Use an {openshiftshort} Route with passthrough encryption to make {brandname}
clusters available on the network.
endif::downstream[]

.Procedure

. Include `spec.expose` in your `Infinispan` CR.
. Specify `Route` as the service type with `spec.expose.type`.
. Optionally add a hostname with `spec.expose.host`.
+
[source,options="nowrap",subs=attributes+]
----
//Community
ifdef::community[]
include::yaml/expose_type_ingress.yaml[]
endif::community[]
//Downstream
ifdef::downstream[]
include::yaml/expose_type_route.yaml[]
endif::downstream[]
----
+
. Apply the changes.
. Verify that the route is available.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_get_routes}

NAME                 CLASS    HOSTS   ADDRESS   PORTS   AGE
{example_crd_name}   <none>   *                 443     73s
----

.Route ports
When you create a route, it exposes a port on the network that accepts client connections and redirects traffic to {brandname} services that listen on port `11222`.

The port where the route is available depends on whether you use encryption or not.

[%header,cols=2*]
|===
|Port
|Description

|`80`
|Encryption is disabled.

|`443`
|Encryption is enabled.
|===
