[id='install-command-line_{context}']
= Installing {ispn_operator} from the command line

[role="_abstract"]
As an alternative to installing {ispn_operator} through the **OperatorHub** on {openshiftshort}, use the `oc` client to create subscriptions.

.Prerequisites

* Have an `oc` client.

.Procedure

. Set up projects.
.. Create a project for {ispn_operator}.
.. If you want {ispn_operator} to control a specific {brandname} cluster only, create a project for that cluster.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_new_project} ${INSTALL_NAMESPACE} <1>
$ {oc_new_project} ${WATCH_NAMESPACE} <2>
----
<1> Creates a project into which you install {ispn_operator}.
<2> Optionally creates a project for a specific {brandname} cluster if you do not want {ispn_operator} to watch all projects.
+
. Create an `OperatorGroup` resource.
+
.Control all {brandname} clusters
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} - << EOF
include::yaml/operator_group.yaml[]
EOF
----
+
.Control a specific {brandname} cluster
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} - << EOF
include::yaml/operator_group_target.yaml[]
EOF
----
+
. Create a subscription for {ispn_operator}.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} - << EOF
include::yaml/operator_subscription.yaml[]
EOF
----
+
[NOTE]
====
If you want to manually approve updates from the {operator_channel} channel, change the value of the `spec.installPlanApproval` field to `Manual`.
====
+
. Verify the installation.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_get_pods} -n ${INSTALL_NAMESPACE}
NAME                                   READY   STATUS
infinispan-operator-<id>               1/1     Running
----
