[id='creating-service-monitor_{context}']
= Creating a Prometheus Service Monitor
Create a Prometheus `ServiceMonitor` that scrapes metrics from a {brandname} cluster.

.Prerequisites

* Have an `oc` client.
* Enable monitoring for user-defined projects on {ocp}.

.Procedure

. Create an authentication secret for the `operator` user.
+
Prometheus needs credentials to authenticate with {brandname} and must use the `operator` user and corresponding password.
+
.. Retrieve the `operator` user credentials.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_get_secret_operator_creds.adoc[]
----
+
.. Create an authentication secret, for example:
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/basic_auth.yaml[]
----
+
.. Add the authentication secret to your {brandname} cluster namespace.
+
[source,options="nowrap",subs=attributes+]
----
$ oc apply -f basic-auth.yaml
----
+
. Create a Prometheus `ServiceMonitor` that scrapes {brandname} metrics.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/prometheus_service_monitor.yaml[]
----
+
. Add the `ServiceMonitor`.
+
[source,options="nowrap",subs=attributes+]
----
$ oc apply -f service-monitor.yaml
----

.Verification

You can check that Prometheus is scraping {brandname} metrics as follows:

. In the {osweb}, select the **</> Developer** perspective and then select **Monitoring**.
. Open the **Dashboard** tab for the namespace where your {brandname} cluster runs.
. Open the **Metrics** tab and confirm that you can query {brandname} metrics such as:
+
----
vendor_cache_manager_default_cluster_size
----

[role="_additional-resources"]
.Additional resources

* link:{link_os_monitoring}
