[id='configuring-sites-automatically_{context}']
= Configuring managed cross-site connections

[role="_abstract"]
Configure {ispn_operator} to establish cross-site views with {brandname} clusters.

.Prerequisites

* Determine a suitable expose type for cross-site replication.
ifdef::community[]
* Create and exchange {openshift} service account tokens for each {brandname} cluster. +
Or, if you are using {k8s}, apply cluster roles and create site access secrets.
endif::community[]
ifdef::downstream[]
* Create and exchange {openshift} service account tokens for each {brandname} cluster.
endif::downstream[]

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Configure the expose type for cross-site replication.
.. Set the value of the `spec.service.sites.local.expose.type` field to one of the following:
+
* `NodePort`
* `LoadBalancer`
* `Route`
.. Optionally specify a port or custom hostname with the following fields:
+
* `spec.service.sites.local.expose.nodePort` if you use a `NodePort` service.
* `spec.service.sites.local.expose.port` if you use a `LoadBalancer` service.
* `spec.service.sites.local.expose.routeHostName` if you use an {openshiftshort} `Route`.

. Specify the number of pods that can send RELAY messages with the `service.sites.local.maxRelayNodes` field.
+
[TIP]
====
Configure all pods in your cluster to send `RELAY` messages for better performance.
If all pods send backup requests directly, then no pods need to forward backup requests.
====

. Provide the name, URL, and secret for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`.
. If {brandname} cluster names or namespaces at the remote site do not match the local site, specify those values with the `clusterName` and `namespace` fields.
+
The following are example `Infinispan` CR definitions for **LON** and **NYC**:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_lon.yaml[]
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_nyc.yaml[]
----
+
[IMPORTANT]
====
Be sure to adjust logging categories in your `Infinispan` CR to decrease log levels for JGroups TCP and RELAY2 protocols.
This prevents a large number of log files from uses container storage.

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_logging.yaml[]
----
====
+
. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.

.Next steps

If your clusters have formed a cross-site view, you can start adding backup locations to caches.

[role="_additional-resources"]
.Additional resources
* link:{xsite_docs}[{brandname} guide to cross-site replication]
