[id='creating-clusters-native-cli_{context}']
= Creating {brandname} clusters

[role="_abstract"]
Create {brandname} clusters with the native CLI plugin, `kubectl-infinispan`.

.Prerequisites

* Install {ispn_operator}.
* Have `kubectl-infinispan` on your `PATH`.

.Procedure

. Run the [command]`infinispan create cluster` command.
+
For example, create a {brandname} cluster with two pods as follows:
+
[source,options="nowrap",subs=attributes+]
----
{kube_client} infinispan create cluster --replicas=3 -Pservice.type=DataGrid infinispan
----
+
[TIP]
====
Add the `--version` argument to control the {brandname} version of your cluster.
For example, `--version={operand_version}`.
If you don't specify the version, {ispn_operator} creates cluster with the latest supported {brandname} version.
====

. Watch {ispn_operator} create the {brandname} pods.
+
[source,options="nowrap",subs=attributes+]
----
{oc_get_pods_w}
----

.Next steps

After you create a {brandname} cluster, use the `{kube_client}` to apply changes to `Infinispan` CR and configure your {brandname} service.

You can also delete {brandname} clusters with `kubectl-infinispan` and re-create them as required.

[source,options="nowrap",subs=attributes+]
----
{kube_client} infinispan delete cluster infinispan
----
