[id='configuring-sites-manually_{context}']
= Configuring cross-site connections manually

[role="_abstract"]
You can specify static network connection details to perform cross-site replication with {brandname} clusters running outside {k8s}.
Manual cross-site connections are necessary in any scenario where access to the Kubernetes API is not available outside the {k8s} cluster where {brandname} runs.

.Prerequisites

Manually connecting {brandname} clusters to form cross-site views requires predictable network locations for {brandname} services.

You need to know the network locations before they are created, which requires you to:

* Have the host names and ports for each {brandname} cluster that you plan to configure as a backup location.
* Have the host name of the `<cluster-name>-site` service for any remote {brandname} cluster that is running on {k8s}. +
You must use the `<cluster-name>-site` service to form a cross-site view between a cluster that {ispn_operator} manages and any other cluster.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set the value of the `spec.service.sites.local.expose.type` field to either `NodePort` or `LoadBalancer`.
. Optionally configure ports with the following fields:
+
* `spec.service.sites.local.expose.nodePort` if you use `NodePort`.
* `spec.service.sites.local.expose.port` if you use `LoadBalancer`.
+
. Provide the name and static URL for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`, for example:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_lon_static.yaml[]
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_nyc_static.yaml[]
----
+
[IMPORTANT]
====
Be sure to adjust logging categories in your `Infinispan` CR to decrease log levels for JGroups TCP and RELAY2 protocols.
This prevents a large number of log files from uses container storage.

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_logging.yaml[]
----
====
+
. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.

.Next steps

If your clusters have formed a cross-site view, you can start adding backup locations to caches.

[role="_additional-resources"]
.Additional resources
* link:{xsite_docs}[{brandname} guide to cross-site replication]
