[id='downloading-code_{context}']
= Downloading code artifacts

[role="_abstract"]
Add your artifacts to an HTTP or FTP server so that {ispn_operator} downloads them to the `{lib_path}` directory on each {brandname} node.

When downloading files, {ispn_operator} can automatically detect the file type.
{ispn_operator} also extracts archived files, such as `zip` or `tgz`, to the filesystem after the download completes.

You can also download Maven artifacts using the `groupId:artifactId:version` format, for example `org.postgresql:postgresql:42.3.1`.

[NOTE]
====
Each time {ispn_operator} creates a {brandname} node it downloads the artifacts to the node.
====

.Prerequisites

* Host your code artifacts on an HTTP or FTP server or publish them to a maven repository.

.Procedure

. Add the `spec.dependencies.artifacts` field to your `Infinispan` CR.
. Do one of the following:
+
* Specify the location of the file to download via `HTTP` or `FTP` as the value of the `spec.dependencies.artifacts.url` field.
* Provide the Maven artifact to download with the `groupId:artifactId:version` format as the value of the `spec.dependencies.artifacts.maven` field.
. Optionally specify a checksum to verify the integrity of the download with the `spec.dependencies.artifacts.hash` field.
+
The `hash` field requires a value is in the format of `<algorithm>:<checksum>` where `<algorithm>` is `sha1|sha224|sha256|sha384|sha512|md5`.
+

+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/dependencies_download.yaml[]
----
+
. Apply the changes.
