[id='configuring-sites-manually_{context}']
= Manually configuring cross-site connections

[role="_abstract"]
You can specify static network connection details to perform cross-site replication with {brandname} clusters running outside {k8s}.
Manual cross-site connections are necessary in any scenario where access to the Kubernetes API is not available outside the {k8s} cluster where {brandname} runs.

.Prerequisites

* Determine a suitable expose type for cross-site replication. +
If you use an {openshiftshort} `Route` you must add a keystore and encrypt RELAY messages between clusters.
* Ensure you have the correct host names and ports for each {brandname} cluster and each `<cluster-name>-site` service.
+
Manually connecting {brandname} clusters to form cross-site views requires predictable network locations for {brandname} services, which means you need to know the network locations before they are created.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Configure the expose type for cross-site replication.
.. Set the value of the `spec.service.sites.local.expose.type` field to one of the following:
+
* `NodePort`
* `LoadBalancer`
* `Route`
.. Optionally specify a port or custom hostname with the following fields:
+
* `spec.service.sites.local.expose.nodePort` if you use a `NodePort` service.
* `spec.service.sites.local.expose.port` if you use a `LoadBalancer` service.
* `spec.service.sites.local.expose.routeHostName` if you use an {openshiftshort} `Route`.

. Provide the name and static URL for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`, for example:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_lon_static.yaml[]
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_nyc_static.yaml[]
----
+
[IMPORTANT]
====
Be sure to adjust logging categories in your `Infinispan` CR to decrease log levels for JGroups TCP and RELAY2 protocols.
This prevents a large number of log files from uses container storage.

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_logging.yaml[]
----
====

. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.

.Next steps

If your clusters have formed a cross-site view, you can start adding backup locations to caches.

[role="_additional-resources"]
.Additional resources
* link:{xsite_docs}[{brandname} guide to cross-site replication]
