[id='exchanging-sa-tokens_{context}']
= Exchanging service account tokens

[role="_abstract"]
After you create service account tokens on your {openshiftshort} clusters, you
add them to secrets on each backup location.
For example, at **LON** you add the service account token for **NYC**.
At **NYC** you add the service account token for **LON**.
{openshiftshort} has two different types of service account tokens, <<non-expiring-tokens,service account token secret>> or <<expiring-tokens, bound service account token>>.
Only a single procedure should be followed.

.Prerequisites

* You have created a service account.

[#non-expiring-tokens]
== Using a service account token secret

NOTE: The token generated by this procedure does not expire.
If you are looking for an expiring token, follow the procedure in <<expiring-tokens>>.

.Procedure

. Log in to an {openshiftshort} cluster.

. Create a service account token secret file as follows.
+
.sa-token.yaml
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: v1
kind: Secret
metadata:
  name: ispn-xsite-sa-token #<1>
  annotations:
    kubernetes.io/service-account.name: "<service-account>" #<2> 
type: kubernetes.io/service-account-token 
----
<1> Specifies the secret name.
<2> Specifies the service account name.

. Create the secret in your {openshiftshort} cluster.
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create -f sa-token.yaml
----

. Retrieve the service account token.
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> get secrets ispn-xsite-sa-token -o jsonpath="{.data.token}" | base64 -d
----
+
The command prints the token in the command line.
Copy it to deploy it in the backup {openshiftshort} cluster(s).

. Log in to the backup {openshiftshort} cluster(s).

. Add the service account token for a backup location with the following command:
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create secret generic <token-secret> --from-literal=token=<token>
----
+
The `<token-secret>` is the name of the secret that needs to be configured in the Infinispan CR.

. Repeat the preceding steps on your other {openshiftshort} clusters.


[#expiring-tokens]
== Using a bound service account token

NOTE: The token generated by this procedure expires.
The token needs to be refreshed periodically, otherwise, the Operator will lose access to the remote {openshiftshort} cluster.
If you are looking for a non-expiring token, follow the procedure in <<non-expiring-tokens>>.

.Procedure

. Log in to an {openshiftshort} cluster.

. Create a bound token for the service account
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create token <service-account>
----
+
The command prints the token in the command line.
Copy it to deploy it in the backup {openshiftshort} cluster(s).
+
TIP: Use the command option `--duration` to set the token expiring date.

. Log in to the backup {openshiftshort} cluster(s).

. Add the service account token for a backup location with the following command:
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create secret generic <token-secret> --from-literal=token=<token>
----
+
The `<token-secret>` is the name of the secret that needs to be configured in the Infinispan CR.

. Repeat the preceding steps on your other {openshiftshort} clusters.

.Renew expiring tokens

When a token expires, a new token needs to be created.
Log in to the backup {openshiftshort} cluster and delete the secret `<token-secret>`.

[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> delete secrets <token-secret>
----

Repeat this procedure to create a new token and generate a new `<token-secret>`.

[role="_additional-resources"]
.Additional resources
* link:{link_os_sa_tokens}
* link:{link_os_sa_bound_tokens}