[id='providing-client-certificates_{context}']
= Providing client certificates

[role="_abstract"]
{ispn_operator} can generate a trust store from certificates in PEM format.

.Procedure

. Specify the name of the secret that contains the client trust store as the value of the `metadata.name` field.
+
[NOTE]
====
The name must match the value of the `spec.security.endpointEncryption.clientCertSecretName` field.
====
+
. Specify the signing certificate, or CA certificate bundle, as the value of the `data.trust.ca` field.
. If you use the `Authenticate` strategy to verify client identities, add the certificate for each client that can connect to {brandname} endpoints with the `data.trust.cert.<name>` field.
+
[NOTE]
====
{ispn_operator} uses the `<name>` value as the alias for the certificate when it generates the trust store.
====
+
. Optionally provide a password for the trust store with the `stringData.truststore-password` field.
+
If you do not provide one, {ispn_operator} sets "password" as the trust store password.
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/cert_auth_certificates.yaml[]
----
+
. Apply the changes.
