[id='configuring_autoscale-{context}']
= Configuring Automatic Scaling
When you create clusters with {cacheservice} nodes, {ispn_operator} can
automatically scale up or down based on memory usage.

{ispn_operator} monitors memory usage for each node in the {brandname} cluster.
If it detects that the {cacheservice} cluster requires additional capacity,
{ispn_operator} creates new nodes rather than evicting entries. Likewise, if it
detects that memory usage is below a certain threshold, {ispn_operator} shuts
down nodes.

.Procedure

. Add the `spec.autoscale` resource to your **Infinispan** CR to enable automatic scaling.
. Configure memory usage thresholds and number of nodes for your cluster as in the following example:
+
[source,options="nowrap",subs=attributes+]
----
spec:
  ...
  autoscale: <1>
    disabled: true <2>
    maxMemUsagePercent: 70 <3>
    maxReplicas: 5 <4>
    minMemUsagePercent: 30 <5>
    minReplicas: 2 <6>
----
+
<1> Enables automatic scaling.
<2> Turns automatic scaling on or off. Use this field to disable automatic scaling without losing your settings. The default value is `false`.
<3> Configures the maximum threshold, as a percentage, for memory usage on each node. When {ispn_operator} detects that any node in the cluster reaches the threshold, it creates a new node if possible. If {ispn_operator} cannot create a new node then it performs eviction when memory usage reaches 100 percent.
<4> Defines the maximum number of number of nodes for the cluster.
<5> Configures the minimum threshold, as a percentage, for memory usage across the cluster. When {ispn_operator} detects that memory usage falls below the minimum, it shuts down nodes.
<6> Defines the minimum number of number of nodes for the cluster.
+
. Apply the changes.
