[id='configuring_sites-{context}']
= Configuring {brandname} Clusters for Cross-Site Replication
Configure {brandname} clusters as backup locations so that they can communicate
over a dedicated JGroups transport channel for replicating data.

.Prerequisites

* Create secrets that contain service account tokens for each backup location.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify a matching name for each {brandname} cluster with metadata.name`.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Provide the name, URL, and secret for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`.
. Specify cluster names and namespaces for {brandname} clusters at each site with the the `clusterName` and `namespace` fields, if necessary.
+
You need to specify cluster names and namespaces for backup locations only if they do not match those for the local {brandname} cluster.
+
The following are example `Infinispan` CR definitions for **LON** and **NYC**:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 3
  service:
    type: DataGrid
    sites:
      local:
        name: LON
        expose:
          type: LoadBalancer
      locations:
        - name: LON
          url: openshift://api.rhdg-lon.openshift-aws.myhost.com:6443
          secretName: lon-token
        - name: NYC
          clusterName: {example_crd_name}
          namespace: {example_namespace}
          url: openshift://api.rhdg-nyc.openshift-aws.myhost.com:6443
          secretName: nyc-token
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 2
  service:
    type: DataGrid
    sites:
      local:
        name: NYC
        expose:
          type: LoadBalancer
      locations:
        - name: NYC
          url: openshift://api.rhdg-nyc.openshift-aws.myhost.com:6443
          secretName: nyc-token
        - name: LON
          clusterName: {example_crd_name}
          namespace: {example_namespace}
          url: openshift://api.rhdg-lon.openshift-aws.myhost.com:6443
          secretName: lon-token
----
+
. Adjust logging levels for cross-site replication as follows:
+
[source,yaml,options="nowrap",subs=attributes+]
----
...
  logging:
    categories:
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: fatal
----
+
The preceding configuration decreases logging for JGroups TCP and RELAY2
protocols to reduce excessive messages about cluster backup operations, which
can result in a large number of log files that use container storage.
+
. Configure nodes with any other {datagridservice} resources.
. Apply the `Infinispan` CRs.
. Check node logs to verify that {brandname} clusters form a cross-site view, for example:
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_logs} {example_crd_name}-0 | grep x-site

INFO  [org.infinispan.XSITE] (jgroups-5,{example_crd_name}-0-<id>) ISPN000439: Received new x-site view: [NYC]
INFO  [org.infinispan.XSITE] (jgroups-7,{example_crd_name}-0-<id>) ISPN000439: Received new x-site view: [NYC, LON]
----

.Next steps

If your clusters have formed a cross-site view, you can start adding backup
locations to caches.

.Reference

* link:#ref_xsite_crd-xsite[Cross-Site Replication Resources]
* link:#adding_backup_locations-caches[Adding Backup Locations to Caches]
* link:{xsite_docs}[{brandname} Guide to Cross-Site Replication]
