[id='securing-cross-site-connections_{context}']
= Securing cross-site connections

:alias: server
:keystore: keystore.p12
:keystore_path: ./{keystore}
:truststore: truststore.p12
:truststore_path: ./{truststore}
:ks_secret: keystore-tls-secret
:ts_secret: truststore-tls-secret

[role="_abstract"]
Add keystores and trust stores so that {brandname} clusters can secure cross-site replication traffic.

You must add a keystore to use an {openshiftshort} `Route` as the expose type for cross-site replication.
Securing cross-site connections is optional if you use a `NodePort` or `LoadBalancer` as the expose type.

[NOTE]
====
Cross-site replication does not support the {k8s} CA service. You must provide your own certificates.
====

.Procedure

. Create the key store and trust store using Keytool (certificate management utility included with Java).

.. Generate a self-signed certificate.
+
[source,bash,options="nowrap",subs=attributes+]
----
keytool -genkey -alias {alias} -keyalg RSA -storetype PKCS12 -keystore {keystore_path} -validity <days> -storepass <password>
----

.. Export the certificate from the key store, so that it can be present in the trust store
+
[source,bash,options="nowrap",subs=attributes+]
----
keytool -export -alias {alias} -keystore {keystore_path} -storetype PKCS12 -rfc -file ~/server_cert.pem -storepass <password>
----

.. Create the trust store and import the certificate
+
[source,bash,options="nowrap",subs=attributes+]
----
keytool -importcert -alias {alias} -keystore {truststore_path} -storetype PKCS12 -file ~/server_cert.pem -storepass <password> -noprompt
----

. Create cross-site encryption secret for each {brandname} cluster.

.. Create keystore secrets.
+
[source,bash,options="nowrap",subs=attributes+]
----
oc create secret generic {ks_secret} \
--from-file={keystore}={keystore_path} \
--from-literal=password=<password> \
--from-literal=type=pkcs12
----

.. Create trust store secrets.
+
[source,bash,options="nowrap",subs=attributes+]
----
oc create secret generic {ts_secret} \
--from-file={truststore}={truststore_path} \
--from-literal=password=<password> \
--from-literal=type=pkcs12
----

. Modify the Infinispan CR for each {brandname} cluster to specify the secret name for the `encryption.transportKeyStore.secretName` and `encryption.routerKeyStore.secretName` fields. 
+ 
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_tls.yaml[]
----

[NOTE]
====
The procedure describes the easier way to encrypt the communication. 
More complex setups are possible in the CR, for example, by setting different certificates for {brandname} Pod and Gossip Router Pod.
Ensure the truststore contains all the required certificate chain for mutual TLS authentication.
====