[id='exposing_external_services-{context}']
= Exposing {brandname} to External Clients
Expose {brandname} clusters to clients running outside {k8s} with external
services.

.Procedure

* Specify an external service type with `spec.expose.type` in your
**Infinispan** CR and then apply the changes.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml_annotated/cr_external_service.yaml[]
----
+
<1> Exposes an external service.
<2> Specifies either a `LoadBalancer` or `NodePort` service resource type.
<3> Defines the port where the external service is exposed. If you do not 
define a port, and the service type is `NodePort`, the platform selects a 
port to use. If the service type is `LoadBalancer`, the exposed port is 
`11222` by default.

//-

`LoadBalancer`:: Use for {k8s} clusters where a load balancer service is
available to handle external network traffic. You can then use the URL for the
load balancer service for client connections.
+
To access {brandname} with unencrypted Hot Rod client connections you must use
a load balancer service.

`NodePort`:: Use for local {k8s} clusters.

.Verification

* Check that the `-external` service is available.

[source,options="nowrap",subs=attributes+]
----
$ {oc_get_services} | grep external

NAME                         TYPE            CLUSTER-IP       EXTERNAL-IP   PORT(S)
{example_crd_name}-external  LoadBalancer    192.0.2.24       <none>        11222/TCP
----

.Reference

* link:#ref_services-reference[Network Services]
