[id='configuring_sites_in_clusters-{context}']
= Configuring Sites in the Same {k8s} Cluster
For evaluation and demonstration purposes, you can configure {brandname} to back up between nodes in the same {k8s} cluster.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set `ClusterIP` as the value of the `spec.service.sites.local.expose.type` field.
. Provide the name and host for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`.
+
The following is an example `Infinispan` CR definition:
+
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-clustera
spec:
  replicas: 1
  expose:
    type: LoadBalancer
  service:
    type: DataGrid
    sites:
      local:
        name: SiteA
        expose:
          type: ClusterIP
      locations:
        - name: SiteA
          host: example-clustera-site <1>
        - name: SiteB
          host: example-clusterb-site
----
<1> The value of the `host` field is the {k8s} service name that resolves to an internal IP address.
+
. Configure nodes with any other {datagridservice} resources.
. Apply the `Infinispan` CRs.
. Check node logs to verify that {brandname} clusters form a cross-site view, for example:
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_grep_xsite.adoc[]
----
