[id='creating_auth_clusters-{context}']
= Creating {brandname} Clusters with Credentials
Create secrets that contain credentials so application users can authenticate to {brandname} nodes. You can then specify the name of the secret in a custom resource `yaml` and spin up clusters with the {ispn_operator}.

.Procedure
. Create a secret that contains credentials for at least one application user.
.. Add an authentication secret `yaml`, for example:
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/cat_connect_secret.adoc[]
----
+
* `type: Opaque` authentication secrets must be `Opaque`.
* `identities.yaml` specifies credentials for application users in `YAML` format. These credentials allow access to data in the {brandname} cluster.
+
[IMPORTANT]
====
Do not use example passwords from this documentation. You should always replace
example credentials with ones that conform to the relevant security guidelines.
====
+
.. Apply the authentication secret `yaml`.
+
[source,options="nowrap",subs=attributes+]
----
$ oc apply -f connect_secret.yaml
----
+
ifdef::productized[]
. Create a custom resource `yaml` for your cluster.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/cat_cr_auth.adoc[]
----
+
* `replicas` specifies the number of nodes in the {brandname} cluster.
* `security.endpointSecret` specifies the authentication secret that contains
your credentials.
+
endif::productized[]
. Apply the custom resource `yaml`.
+
ifndef::productized[]
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_apply_cr_auth.adoc[]
----
+
endif::productized[]
ifdef::productized[]
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_apply_local_cr_auth.adoc[]
----
endif::productized[]
+
. Verify that the {ispn_operator} creates the pods.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_get_pods_w.adoc[]
----
