[id='install-olm_{context}']
= Installing {ispn_operator} on {openshift}

[role="_abstract"]
Create subscriptions to {ispn_operator} on {openshiftshort} so you can install different {brandname} versions and receive automatic updates.

Automatic updates apply to {ispn_operator} first and then for each {brandname} node.
{ispn_operator} updates clusters one node at a time, gracefully shutting down each node and then bringing it back online with the updated version before going on to the next node.

.Prerequisites

* Access to **OperatorHub** running on {openshiftshort}. Some {openshiftshort} environments, such as {ocp}, can require administrator credentials.
ifdef::community[]
* Ensure the Operator Lifecycle Manager (OLM) is installed.
endif::community[]
* Have an {openshiftshort} project for {ispn_operator} if you plan to install it into a specific namespace.

.Procedure

. Log in to the {osweb}.
. Navigate to **OperatorHub**.
. Find and select {ispn_operator}.
. Select **Install** and continue to **Create Operator Subscription**.
. Specify options for your subscription.
+
Installation Mode:: You can install {ispn_operator} into a **Specific** namespace or **All** namespaces.
//Community
ifdef::community[]
Update Channel:: Subscribe to updates for {ispn_operator} versions.
Approval Strategies:: When new {brandname} versions become available, you can install updates manually or let {ispn_operator} install them automatically.
endif::community[]
//Downstream
ifdef::downstream[]
Update Channel:: Get updates for {ispn_operator} {operator_channel}.
Approval Strategies:: Automatically install updates from the {operator_channel} channel or require approval before installation.
endif::downstream[]
+
. Select **Subscribe** to install {ispn_operator}.
. Navigate to **Installed Operators** to verify the {ispn_operator} installation.
