[id='adding_credentials-{context}']
= Adding Custom Credentials
Configure access to {brandname} cluster endpoints with custom credentials.

.Procedure

. Define custom credentials in an `identities.yaml` file.
. Create an authentication secret from `identities.yaml` as follows:
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_create} secret generic --from-file=identities.yaml connect-secret
----
+
. Specify the authentication secret with `spec.security.endpointSecretName` in
your `Infinispan` CR and then apply the changes.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml_annotated/cr_auth.yaml[]
----
+
<1> Specifies the name of the authentication secret that contains your
credentials.

.Verification

Modifying `spec.security.endpointSecretName` triggers a cluster restart. You
can watch the {brandname} cluster as {ispn_operator} applies changes:

[source,options="nowrap",subs=attributes+]
----
$ {oc_get_pods_w}
----

When the {brandname} cluster is running, verify your custom credentials as
follows:

. Open a remote shell to a {brandname} node, for example:
+
[source,options="nowrap",subs=attributes+]
----
$ {kubectl_exec}
----
. Check that credentials exist in the `users.properties` file.
+
[source,options="nowrap",subs=attributes+]
----
$ cat {conf_path}/users.properties
----
+
. Exit the remote shell.
+
[source,options="nowrap",subs=attributes+]
----
$ exit
----
