[id='creating_service_monitor-{context}']
= Creating a Prometheus Service Monitor
Define a service monitor instances that configures Prometheus to monitor your
{brandname} cluster.

.Prerequisites

* Set up a Prometheus stack on your {k8s} cluster.

.Procedure

. Retrieve the credentials for {ispn_operator}.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/basic_auth.yaml[]
----
+
. Create an authentication secret that contains the credentials. +
This allows Prometheus to authenticate with your {brandname} cluster and retrieve metrics.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/basic_auth.yaml[]
----
+
<1> Specifies the **operator** user.
<2> Specifies the corresponding password.
+
. Add the authentication secret to your Prometheus namespace.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} basic-auth.yaml
----
+
. Create a service monitor that configures Prometheus to monitor your {brandname} cluster.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/service_monitor.yaml[]
----
+
<1> Names the service monitor instances.
<2> Specifies the namespace of your Prometheus stack.
<3> Sets the port of `11223` for the {brandname} metrics endpoint.
<4> Sets the path where {brandname} exposes metrics.
<5> Specifies the authentication secret with {ispn_operator} credentials.
<6> Specifies the namespace of your {brandname} cluster.
<7> Specifies the name of your {brandname} cluster.
+
. Add the service monitor instance to your Prometheus namespace.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} service-monitor.yaml
----

[role="_additional-resources"]
.Additional resources

* {link_prometheus_operator}
* {link_os_monitoring}
