[id='configuring-sites-in-clusters_{context}']
= Configuring sites in the same {k8s} cluster

[role="_abstract"]
For evaluation and demonstration purposes, you can configure {brandname} to back up between pods in the same {k8s} cluster.

[IMPORTANT]
====
Using `ClusterIP` as the expose type for cross-site replication is intended for demonstration purposes only.
It would be appropriate to use this expose type only to perform a temporary proof-of-concept deployment on a laptop or something of that nature.
====

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set `ClusterIP` as the value of the `spec.service.sites.local.expose.type` field.
. Provide the name of the {brandname} cluster that acts as a backup location with `spec.service.sites.locations.clusterName`.
. If both {brandname} clusters have the same name, specify the namespace of the backup location with `spec.service.sites.locations.namespace`.
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_cluster_ip.yaml[]
----
+
. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.
