[id='configuring_sites_in_clusters']
= Configuring Sites in the Same {k8s} Cluster
For evaluation and demonstration purposes, you can configure {brandname} to back up between nodes in the same {k8s} cluster.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set `ClusterIP` as the value of the `spec.service.sites.local.expose.type` field.
. Provide the {brandname} cluster hostname as the URL for each backup location with `spec.service.sites.locations`.
+
The following is an example `Infinispan` CR definition:
+
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-clustera
spec:
  replicas: 1
  expose:
    type: LoadBalancer
  service:
    type: DataGrid
    sites:
      local:
        name: SiteA
        expose:
          type: ClusterIP
      locations:
        - name: SiteA
          url: infinispan+xsite://example-clustera-site <1>
        - name: SiteB
          url: infinispan+xsite://example-clusterb-site
----
<1> The value of the `url` field is the {k8s} service name that resolves to an internal IP address.
+
. Configure nodes with any other {datagridservice} resources.
. Apply the `Infinispan` CRs.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.
