[id='exposing-routes_{context}']
= Exposing {brandname} through a Route

//Community
ifdef::community[]
[role="_abstract"]
Use a {k8s} Ingress or an {openshiftshort} `Route` with passthrough encryption to make {brandname} clusters available on the network.
endif::community[]
//Downstream
ifdef::downstream[]
[role="_abstract"]
Use an {openshiftshort} `Route` with passthrough encryption to make {brandname} clusters available on the network.
endif::downstream[]

.Procedure

. Include `spec.expose` in your `Infinispan` CR.
. Specify `Route` as the service type with the `spec.expose.type` field.
. Optionally add a hostname with the `spec.expose.host` field.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/expose_type_route.yaml[]
----
+
. Apply the changes.
. Verify that the route is available.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_get_routes}

NAME                 CLASS    HOSTS   ADDRESS   PORTS   AGE
{example_crd_name}   <none>   *                 443     73s
----

.`Route` ports
When you create a `Route`, it exposes a port on the network that accepts client connections and redirects traffic to {brandname} services that listen on port `11222`.

The port where the `Route` is available depends on whether you use encryption or not.

[%header,cols=2*]
|===
|Port
|Description

|`80`
|Encryption is disabled.

|`443`
|Encryption is enabled.
|===
