[id='creating_sa_tokens-{context}']
= Creating Service Account Tokens
Traffic between independent {openshiftshort} installations occurs through a Kubernetes API. {ocp} clusters use tokens to authenticate with and access the API.

To enable cross-site replication between {brandname} clusters you must add tokens to the namespace on each site. For example, **LON** needs a secret with the token for **NYC**. **NYC** also needs a secret with the token for **LON**.

.Procedure

. Create service account tokens on each {openshiftshort} instance.
+
For example, on **LON** create a token for **NYC** as follows:
+
[source,options="nowrap",subs=attributes+]
----
$ oc create sa lon
serviceaccount/lon created
----
+
. Retrieve each service account token.
+
The following example shows the service account token for **LON**:
+
[source,options="nowrap",subs=attributes+]
----
$ oc sa get-token lon

eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9...
----
+
. Create secrets that contain service account tokens for the backup locations.
.. Log in to {ocp} at **NYC**.
.. Add the service account token to a `lon-token` secret.
+
[source,options="nowrap",subs=attributes+]
----
oc create secret generic lon-token --from-literal=token=eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9...
----
+
.. Repeat the preceding steps to create a `nyc-token` secret on **LON**.

After you add service account tokens to each backup location, the
{openshiftshort} instances can authenticate with each other so that {brandname}
clusters can form cross-site views.

.Reference

link:{link_os_sa_tokens}
