[id='configuring-sites-in-clusters_{context}']
= Configuring sites in the same {k8s} cluster
For evaluation and demonstration purposes, you can configure {brandname} to back up between nodes in the same {k8s} cluster.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set `ClusterIP` as the value of the `spec.service.sites.local.expose.type` field.
. Provide the {brandname} cluster hostname as the URL for each backup location with `spec.service.sites.locations`.
+
The following is an example `Infinispan` CR:
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_cluster_ip.yaml[]
----
+
[NOTE]
====
In the `spec.service.sites.locations.url` field, "example-cluster*-site" is the {k8s} service name that resolves to an internal IP address.
====
+
. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.
