[id="exchanging-service-account-tokens-{context}"]
= Exchanging service account tokens

[role="_abstract"]
Generate service account tokens on your {openshiftshort} clusters and add them into secrets at each backup location.
The tokens that you generate in this procedure do not expire.
For bound service account tokens, see link:#exchanging-bound-service-account-tokens-cross-site[Exchanging bound service account tokens].

.Prerequisites

* You have created a service account.

.Procedure

. Log in to your {openshiftshort} cluster.

. Create a service account token secret file as follows:
+
.sa-token.yaml
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_sa_token.yaml[]
----
<1> Specifies the name of the secret.
<2> Specifies the service account name.

. Create the secret in your {openshiftshort} cluster:
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create -f sa-token.yaml
----

. Retrieve the service account token:
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> get secrets ispn-xsite-sa-token -o jsonpath="{.data.token}" | base64 -d
----
+
The command prints the token in the terminal.
. Copy the token for deployment in the backup {openshiftshort} cluster.

. Log in to the backup {openshiftshort} cluster.

. Add the service account token for a backup location:
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create secret generic <token-secret> --from-literal=token=<token>
----
+
The `<token-secret>` is the name of the secret configured in the `Infinispan` CR.

.Next steps

* Repeat the preceding steps on your other {openshiftshort} clusters.

[role="_additional-resources"]
.Additional resources
* link:{link_os_sa_bound_tokens}