[id='cache_templates-{context}']
= Creating {brandname} Caches from Templates
Complete the following steps to create caches on {datagridservice} clusters
using cache configuration templates.

.Prerequisites

* Identify the cache configuration template you want to use for your cache. You
can find a list of available configuration templates in {brandname} Console.

.Procedure

. Create a `Cache` CR that specifies the name of the template you want to use.
+
For example, the following CR creates a cache named "mycache" that uses the `org.infinispan.DIST_SYNC` cache configuration template:
+
[source,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: mycachedefinition <1>
spec:
  clusterName: {example_crd_name} <2>
  name: mycache <3>
  templateName: org.infinispan.DIST_SYNC <4>
----
+
<1> Names the `Cache` CR.
<2> Specifies the name of the target {brandname} cluster where you want {ispn_operator} to create the cache.
<3> Names the {brandname} cache instance.
<4> Specifies the `infinispan.org` cache configuration template to create the cache.
+
. Apply the `Cache` CR, for example:
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} mycache.yaml
cache.infinispan.org/mycachedefinition created
----
