[id='xsite-disable-gr_{context}']
= Disable local Gossip Router and service

[role="_abstract"]
Only a single Gossip Router is required to route the cross-site traffic, however the {brandname} operator starts a Gossip Route on each site.
You can disable the Gossip Router in one of the sites to save resources.

.Prerequisites

* A working Gossip Router.
+
It can be an external Gossip Router, i.e., not managed by the {brandname} operator.

.Procedure

To disable the Gossip Router on a site:

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set `spec.service.sites.local.discovery.launchGossipRouter` to false.
. Specify the `url` to connect to the remote site `spec.service.sites.locations.url`.
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_disable_gossip_router.yaml[]
----

To connect to a remote site with Gossip Router disabled:

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set `spec.service.sites.local.discovery.launchGossipRouter` to false.
. Do not specify `spec.service.sites.locations.url`.
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_local_gossip_router.yaml[]
----


.Next steps

If your clusters have formed a cross-site view, you can start adding backup locations to caches.

[role="_additional-resources"]
.Additional resources
* link:{xsite_docs}[{brandname} guide to cross-site replication]
