[id='adding-backup-locations_{context}']
= Adding backup locations to caches

[role="_abstract"]
When you configure {brandname} clusters to perform cross-site replication, you
can add backup locations to your cache configurations.

.Procedure

. Create cache configurations that name remote sites as backup locations.
+
{brandname} replicates data based on cache names.
For this reason, site names in your cache configurations must match site names, `spec.service.sites.local.name`, in your `Infinispan` CRs.
+
. Configure backup locations to go offline automatically with the `take-offline` element.
.. Set the amount of time, in milliseconds, before backup locations go offline with the `min-wait` attribute.
. Define any other valid cache configuration.
. Add backup locations to the named cache on all sites in the global cluster.
+
For example, if you add **LON** as a backup for **NYC** you should add **NYC**
as a backup for **LON**.

The following configuration examples show backup locations for caches:

* **NYC**
+
[source,xml,options="nowrap",subs=attributes+]
----
include::xml/nyc-dist-cache.xml[]
----

* **LON**
+
[source,xml,options="nowrap",subs=attributes+]
----
include::xml/lon-repl-cache.xml[]
----

[role="_additional-resources"]
.Additional resources
* link:{xsite_docs}[{brandname} Guide to Cross-Site Replication]
