[id='creating_services-{context}']
= Creating Services
Define the `.spec.service.type` resource to create {cacheservice} and
{datagridservice} nodes with {ispn_operator}.

By default, {ispn_operator} creates {brandname} clusters configured as a
{cacheservice}.

.Procedure

* Specify the service type for {brandname} clusters with `spec.service.type` in
your **Infinispan** CR and then apply the changes.

For example, create {datagridservice} clusters as follows:

[source,options="nowrap",subs=attributes+]
----
spec:
  ...
  service:
    type: DataGrid
----

[IMPORTANT]
====
You cannot change `.spec.service.type` after you create {brandname} clusters.

For example, if you create a cluster of {cacheservice} nodes, you cannot change
the service type to {datagridservice}. In this case you must create a new
cluster with {datagridservice} nodes in a different {k8s} namespace.
====

.Reference

* link:#ref_cache_service_crd-nodes[Cache Service Resources]
* link:#ref_datagrid_service_crd-nodes[Data Grid Service Resources]
