[id='configuring-sites-manually_{context}']
= Specifying static hosts and ports for {brandname} clusters

[role="_abstract"]
Specify static hosts and ports for {brandname} clusters so they can establish connections and form cross-site views.

.Prerequisites

* Have the host names and ports for each {brandname} cluster that you plan to configure as a backup location.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Provide the name and static URL for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`, for example:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_lon_static.yaml[]
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_nyc_static.yaml[]
----
+
[IMPORTANT]
====
Be sure to adjust logging categories in your `Infinispan` CR to decrease log levels for JGroups TCP and RELAY2 protocols.
This prevents a large number of log files from uses container storage.

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_logging.yaml[]
----
====
+
. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.

.Next steps

If your clusters have formed a cross-site view, you can start adding backup
locations to caches.
