[id='creating_caches_cli-{context}']
= Creating Caches with {brandname} CLI
Add caches to your {brandname} cluster with the CLI.

.Prerequisites

* Download the server distribution so you can run the CLI.
* Retrieve the necessary client connection details.

.Procedure

. Create a file with a cache configuration in XML or JSON format, for example:
+
[source,bash,options="nowrap",subs=attributes+]
----
cat > infinispan.xml<<EOF
<infinispan>
   <cache-container>
      <distributed-cache name="mycache">
         <encoding>
            <key media-type="application/x-protostream"/>
            <value media-type="application/x-protostream"/>
         </encoding>
      </distributed-cache>
   </cache-container>
</infinispan>
EOF
----
+
. Create a CLI connection to your {brandname} cluster.
+
[source,bash,options="nowrap",subs=attributes+]
----
$ bin/cli.sh -c https://$SERVICE_HOSTNAME:$PORT --trustall
----
+
Replace `$SERVICE_HOSTNAME:$PORT` with the hostname and port where {brandname} is available on the network.
+
. Enter your {brandname} credentials when prompted.
. Add the cache with the [command]`create cache` command and the [command]`--file` option.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> create cache --file=infinispan.xml mycache
----
+
. Verify the cache exists with the [command]`ls` command.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> ls caches
mycache
----
+
. Optionally retrieve the cache configuration with the [command]`describe` command.
+
[source,bash,options="nowrap",subs=attributes+]
----
[//containers/default]> describe caches/mycache
----

[role="_additional-resources"]
.Additional resources

* link:{server_docs}#downloading_server_distributions[Downloading Server Distributions]
* link:{cli_docs}[Using the {brandname} Command Line Interface]
