= Setting Up Prometheus
Set up Prometheus so it can authenticate with and monitor {brandname} clusters.

.Prerequisites

* Install the Prometheus Operator.
* Create a running Prometheus instance.

.Procedure

. Add an authentication secret to your Prometheus namespace.
+
This secret allows Prometheus to authenticate with your {brandname} cluster. You can find {brandname} credentials in the authentication secret in your {ispn_operator} namespace.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml_annotated/basic_auth.yaml[]
----
+
<1> Specifies an application user. `developer` is the default application user.
<2> Specifies a corresponding password.
+
. Create a service monitor instance that configures Prometheus to monitor your {brandname} cluster.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml_annotated/service_monitor.yaml[]
----
+
<1> Names the service monitor.
<2> Specifies your Prometheus namespace.
<3> Specifies the name of the authentication secret that has {brandname} credentials.
<4> Specifies the name of the authentication secret that has {brandname} credentials.
<5> Specifies that {brandname} endpoints use encryption. If you do not use TLS, remove `spec.endpoints.scheme`.
<6> Specifies the Common Name (CN) of the TLS certificate for {brandname} encryption. If you use an {openshiftshort} service certificate, the CN matches the `metadata.name` resource for your {brandname} cluster. If you do not use TLS, remove `spec.endpoints.tlsConfig`.
<7> specifies the {ispn_operator} namespace.
<8> specifies the name of the {brandname} cluster.
