[id='secure_credentials_{context}']
= Securing custom {brandname} configuration

[role="_abstract"]
Securely define and store custom {brandname} Server configuration.
To protect sensitive text strings such as passwords, add the entries in a credential store rather than directly in the {brandname} Server configuration.

.Prerequisites
* Have a valid {brandname} configuration in XML, YAML, or JSON format.

.Procedure
. Create a `CredentialStore Secret` file.
. Use the `data` field to specify the credentials and its aliases.
+
.user-secret.yaml
[source,yaml]
----
include::yaml/credential_store_secret.yaml[]
----

. Apply your Secret file.
+
[source,options="nowrap",subs=attributes+]
----
{oc_apply_cr} user-secret.yaml
----
. Open the `Infinispan` CR for editing.
. In the `spec.security.credentialStoreSecretName` field, specify the name of the credential store secret.
+
.Infinispan CR
[source,yaml]
----
include::yaml/credential_store.yaml[]
----

. Apply the changes.
. Open your {brandname} Server configuration for editing.
. Add a `credential-reference` to your configuration.
.. Specify the `credentials` as the name of the `store`.
.. Specify the `alias` attribute as one of the keys defined in your credential secret.
+
.{brandname}.xml
----
include::xml/alias_credentials_config.xml[]
----

[role="_additional-resources"]
.Additional resources
* link:{server_docs}#credential-keystore-references_credential-keystores[Credential store references]
