[id='cache_auth-{context}']
= Adding Credentials for {ispn_operator}
{ispn_operator} must authenticate with {datagridservice} clusters to create caches.
You add credentials to a secret so that {ispn_operator} can access your cluster when creating caches.

The following procedure explains how to add credentials to a new secret.
If you already have a custom secret that contains credentials, you can use that instead of creating a new one.

.Procedure

. Define a **Secret** object type that provides valid user credentials for
accessing {datagridservice} clusters in a `StringData` map.
+
For example, create an `basic-auth.yaml` file that provides credentials for
the `developer` user as follows:
+
[source,options="nowrap",subs=attributes+]
----
apiVersion: v1
stringData:
  username: developer <1>
  password: G8ZdJvSaY3lOOwfM <2>
kind: Secret
metadata:
  name: basic-auth <3>
type: Opaque
----
<1> Names a user that can create caches.
<2> Specifies the password that corresponds to the user.
<3> Specifies a name for the secret.
+
. Create a secret from the file, as in the following example:
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} basic-auth.yaml
----
