[id='connecting-cli_{context}']
= Connecting to {brandname} clusters with remote shells

[role="_abstract"]
Start a remote shell session to {brandname} clusters and use the command line interface (CLI) to work with {brandname} resources and perform administrative operations.

.Prerequisites

* Have `kubectl-infinispan` on your `PATH`.
* Have valid {brandname} credentials.

.Procedure

. Run the [command]`infinispan shell` command to connect to your {brandname} cluster.
+
[source,bash,options="nowrap",subs=attributes+]
----
$ {kube_client} infinispan shell infinispan
----
+
[NOTE]
====
The `kubectl-infinispan` plugin automatically detects the default `developer` credentials and uses them to authenticate to {brandname}.
If you are using custom credentials, specify a {brandname} user with the `--username` argument and enter the corresponding password when prompted.
====
+
. Perform CLI operations as required.
+
[TIP]
====
Press the tab key or use the [command]`help` command to view available options and command manpages.
====
+
. Use the [command]`quit` command to end the remote shell session.

[role="_additional-resources"]
.Additional resources
* link:{cli_docs}[Using the {brandname} Command Line Interface]
