[id='adding-custom-env-vars{context}']
= Adding environment variables to {brandname} pods

[role="_abstract"]
Configure custom environment variables for the {brandname} nodes managed by the {ispn_operator}. 
You can use literal values to tune behavior, such as `JAVA_OPTS`, or reference values from Secrets and ConfigMaps for sensitive data like credentials. To get more information on valid environment variables accepted by a

.Procedure

. Open your `Infinispan` CR for editing.
. Define environment variables in the `spec.container.env` section.
+
[NOTE]
====
Adding or modifying environment variables triggers a **rolling update** of the {brandname} cluster to apply the changes to all pods.
====
+
.Custom environment variables
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/custom_envvars.yaml[]
----
. Apply your `Infinispan` CR.

.Verification
Confirm the environment variables are present in the pods:
[source,options="nowrap",subs=attributes+]
----
{oc} exec <pod-name> -- printenv | grep JAVA_OPTIONS
----
[IMPORTANT]
====
Defining `JAVA_OPTIONS` alongside `spec.container.extraJvmOpts` will result in only one of the two being effectively applied. Do not to use them simultaneously. The same restriction applies to `CLI_JAVA_OPTIONS` and `spec.container.cliExtraJvmOpts`.
====

.Additional resources
* link:{server_docs}#jvm-settings-for-server_server[JVM settings for Infinispan]