[id='creating-caches-hotrod_{context}']
= Creating caches from Hot Rod clients

[role="_abstract"]
You can remotely create caches on {brandname} clusters running on {k8s} with Hot Rod clients.
However, {brandname} recommends that you create caches using {brandname} Console, the CLI, or with `Cache` CRs instead of with Hot Rod clients.

[discrete]
== Programmatically creating caches

The following example shows how to add cache configurations to the `ConfigurationBuilder` and then create them with the `RemoteCacheManager`:

[source,java,options="nowrap",subs=attributes+]
----
include::java/RemoteCacheConfigurationBuilder.java[]
----

This example shows how to create a cache named CacheWithXMLConfiguration using the `XMLStringConfiguration()` method to pass the cache configuration as XML:

[source,java,options="nowrap",subs=attributes+]
----
include::java/RemoteCacheWithXml.java[]
----

[discrete]
== Using Hot Rod client properties

When you invoke `cacheManager.getCache()` calls for named caches that do not exist, {brandname} creates them from the Hot Rod client properties instead of returning null.

Add cache configuration to `hotrod-client.properties` as in the following example:

[source,options="nowrap",subs=attributes+]
----
# Add cache configuration
infinispan.client.hotrod.cache.my-cache.configuration=<infinispan><cache-container><distributed-cache name=\"my-cache\"/></cache-container></infinispan>
infinispan.client.hotrod.cache.another-cache.configuration_uri=file:/path/to/configuration.xml
----
