[id='creating-sa-tokens-openshift_{context}']
= Creating service account tokens for managed cross-site connections

[role="_abstract"]
Generate service account tokens on {openshiftshort} clusters that allow {ispn_operator} to automatically discover {brandname} clusters and manage cross-site connections.

//Community content
ifdef::community[]
This procedure is specific to {openshiftshort} clusters.
If you are using another Kubernetes distribution, you should create site access secrets instead.
endif::community[]

.Prerequisites

* Ensure all {openshiftshort} clusters have access to the Kubernetes API. +
{ispn_operator} uses this API to manage cross-site connections.
+
[NOTE]
====
{ispn_operator} does not modify remote {brandname} clusters.
The service account tokens provide read only access through the Kubernetes API.
====

.Procedure

. Log in to an {openshiftshort} cluster.
. Create a service account.
+
For example, create a service account at **LON**:
+
[source,options="nowrap",subs=attributes+]
----
$ oc create sa lon
serviceaccount/lon created
----
+
. Add the view role to the service account with the following command:
+
[source,options="nowrap",subs=attributes+]
----
$ oc policy add-role-to-user view system:serviceaccount:<namespace>:lon
----
+
. If you use a `NodePort` service to expose {brandname} clusters on the network, you must also add the `cluster-reader` role to the service account:
+
[source,options="nowrap",subs=attributes+]
----
$ oc adm policy add-cluster-role-to-user cluster-reader -z <service-account-name> -n <namespace>
----
+
. Repeat the preceding steps on your other {openshiftshort} clusters.
. Exchange service account tokens on each {openshiftshort} cluster.

[role="_additional-resources"]
.Additional resources
* link:{link_os_sa_tokens}
