[id='creating_caches_operator-{context}']
= Creating Caches with {ispn_operator}
To create caches with {ispn_operator}, you use **Cache** CRs to add caches
from templates or XML configuration.

[IMPORTANT]
====
Creating caches with {ispn_operator} is available as a technology preview.

Technology Preview features or capabilities are not supported with Red Hat
production service-level agreements (SLAs) and might not be functionally
complete. Red Hat does not recommend using them for production. These features
provide early access to upcoming product features, enabling customers to test
functionality and provide feedback during the development process.
====

When using **Cache** CRs, the following rules apply:

* **Cache** CRs apply to {datagridservice} nodes only.
* You can create a single cache for each **Cache** CR.
* If your **Cache** CR contains both a template and an XML configuration, {ispn_operator} uses the template.
* If you edit caches in the {osweb}, the changes are reflected through the user interface but do not take effect on the {brandname} cluster. You cannot edit caches. To change cache configuration, you must first delete the cache through the console or CLI and then re-create the cache.
* Deleting **Cache** CRs in the {osweb}, does not remove caches from {brandname} clusters. You must delete caches through the console or CLI.

.Reference

link:{link_tech_preview}
