[id='securing-cross-site-connections_{context}']
= Securing cross-site connections

[role="_abstract"]
Add keystores, and optional trust stores, so that {brandname} clusters can encrypt RELAY messages and secure cross-site replication traffic.

.Prerequisites

* Have a PKCS12 keystore that {brandname} can use to encrypt and decrypt RELAY messages.
+
You must provide a keystore for relay pods and router pods to secure cross-site connections. +
The keystore can be the same for relay pods and router pods or you can provide separate keystores for each. +
You can also use the same keystore for each {brandname} cluster or a unique keystore for each cluster.

* Optionally have a trust store that contains part of the certificate chain or root CA certificate that verifies public certificates for {brandname} relay pods and router pods.
+
By default, {brandname} uses the Java trust store to verify public certificates.

.Procedure

. Create cross-site encryption secrets.
.. Create keystore secrets.
.. Create trust store secrets if you do not want to use the default Java trust store.
. Modify the `Infinispan` CR for each {brandname} cluster to specify the secret name for the `encryption.transportKeyStore.secretName` and `encryption.routerKeyStore.secretName` fields.
. Configure any other fields to encrypt RELAY messages as required and then apply the changes.
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_tls.yaml[]
----
