[id='configuring_sites-{context}']
= Specifying Static Hosts and Ports for {brandname} Clusters
Specify static hosts and ports for {brandname} clusters so they can establish connections and form cross-site views.

.Prerequisites

* Have the host names and ports for each {brandname} cluster that you plan to configure as a backup location.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Provide the name and static URL for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`, for example:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 3
  service:
    type: DataGrid
    sites:
      local:
        name: LON
        expose:
          type: LoadBalancer
      locations:
        - name: LON
          url: infinispan+xsite://infinispan-lon.myhost.com:7900
        - name: NYC
          url: infinispan+xsite://infinispan-nyc.myhost.com:7900
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 2
  service:
    type: DataGrid
    sites:
      local:
        name: NYC
        expose:
          type: LoadBalancer
      locations:
        - name: NYC
          url: infinispan+xsite://infinispan-nyc.myhost.com:7900
        - name: LON
          url: infinispan+xsite://infinispan-lon.myhost.com
----
+
. Adjust logging levels for cross-site replication as follows:
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_logging.yaml[]
----
+
The preceding configuration decreases logging for JGroups TCP and RELAY2
protocols to reduce excessive messages about cluster backup operations, which
can result in a large number of log files that use container storage.
+
. Configure nodes with any other {datagridservice} resources.
. Apply the `Infinispan` CRs.
. Check node logs to verify that {brandname} clusters form a cross-site view, for example:
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_grep_xsite.adoc[]
----

.Next steps

If your clusters have formed a cross-site view, you can start adding backup
locations to caches.

.Reference

* link:#ref_xsite_crd_manual-xsite_manual[Cross-Site Replication Resources]
* link:#adding_backup_locations-caches[Adding Backup Locations to Caches]
* link:{xsite_docs}[{brandname} Guide to Cross-Site Replication]
