[id="using-bound-service-account-token-secret-{context}"]
= Using a bound service account token

[role="_abstract"]
Create a service account token with a limited lifespan.
You must refresh the token periodically to prevent {ispn_operator} from loosing access to the remote {openshiftshort} cluster.

.Prerequisites

* You have created a service account.

.Procedure

. Log in to your {openshiftshort} cluster.

. Create a bound token for the service account.
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create token <service-account>
----
+

[NOTE]
====
By default, service account tokens are valid for one hour.
Use the command option `--duration` to specify the lifespan in seconds..
====
+
The command prints the token in the terminal.
. Copy the token to deploy it in the backup {openshiftshort} cluster(s).

. Log in to the backup {openshiftshort} cluster(s).

. Add the service account token for a backup location with the following command:
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> create secret generic <token-secret> --from-literal=token=<token>
----
+
The `<token-secret>` is the name of the secret that needs to be configured in the Infinispan CR.

. Repeat the preceding steps on your other {openshiftshort} clusters.

[discrete]
=== Renewing expiring tokens
When a token expires, create a new token.

. Log in to the backup {openshiftshort} cluster.

. Delete the expired secret `<token-secret>`.
+
[source,bash,options="nowrap",subs=attributes+]
----
oc -n <namespace> delete secrets <token-secret>
----

. Repeat the procedure to create a new token and generate a new `<token-secret>`.