[id='getting_credentials-{context}']
= Retrieving Cluster Credentials
You can retrieve credentials for your {brandname} clusters as base64-encoded strings from secrets in your cluster namespace.

If you do not create secrets and credentials when you create clusters, the {ispn_operator} automatically generates them with the following defaults:

Default usernames::
+
* Management user is `admin`.
* Application user is `developer`.

Default credentials secrets::
+
* `{example_crd_name}-mgmt-generated-secret` contains credentials for the management user.
* `{example_crd_name}-app-generated-secret` contains credentials for the application user.

.Procedure
* Get the credentials from the secret. For example, to get the password for the application user from the default secret:
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_get_app_secret.adoc[]
----
+
[TIP]
====
Use the `jp` JSON processor to retrieve credentials as follows:

[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_get_app_secret_jp.adoc[]
----
====
