[id='using_platform_certs-{context}']
= Generating Service Certificates for Encryption
The {ispn_operator} can generate {openshift} service certificates that:

* Consist of a certificate, `tls.crt`, and key, `tls.key`, in PEM format that
{openshiftshort} stores in a secret.
* Are signed by the {openshiftshort} CA, are valid for one year, and are
automatically replaced before expiration.

.Procedure

. Define custom resources to use service certificates for encryption.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml_annotated/cr_tls_service.yaml[]
----
+
<1> encrypts traffic to and from {brandname} endpoints.
<2> configures {brandname} to service certificates.
<3> adds the {openshiftshort} annotation.
<4> names the encryption secret.
+
. Apply the custom resource with `{oc_apply_cr}`.
. Use `{oc_get_pods_w}` to watch the {ispn_operator} apply the custom resources.
. Retrieve `tls.crt` from the secret to create truststores for clients.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/oc_get_secret_tls.adoc[]
----
