[id='creating_services-{context}']
= Creating {brandname} Services
Define the `.spec.service.type` resource to create {cacheservice} and
{datagridservice} pods with {ispn_operator}.

By default, {ispn_operator} creates {brandname} clusters with {cacheservice}
pods.

.Procedure

* Set the service type for {brandname} pods in your custom resource definition and then apply the changes.

For example, create {datagridservice} clusters as follows:

[source,options="nowrap",subs=attributes+]
----
spec:
  ...
  service:
    type: DataGrid
----

[IMPORTANT]
====
You cannot change the `.spec.service.type` resource after you create
{brandname} clusters.

For example, if you create a cluster of {cacheservice} pods, you cannot change
the service type to {datagridservice}. In this case you must create a new
cluster with {datagridservice} pods in a different {k8s} namespace.
====

.Reference

* link:#ref_cache_service_crd-services[Cache Service Resources]
* link:#ref_datagrid_service_crd-services[Data Grid Service Resources]
