[id='backing-up-clusters_{context}']
= Backing up {brandname} clusters

[role="_abstract"]
Create a backup file that stores {brandname} cluster state to a persistent volume.

.Prerequisites

* Create an `Infinispan` CR with `spec.service.type: DataGrid`.
* Ensure there are no active client connections to the {brandname} cluster.
+
{brandname} backups do not provide snapshot isolation and data modifications are not written to the archive after the cache is backed up. +
To archive the exact state of the cluster, you should always disconnect any clients before you back it up.

.Procedure

. Name the `Backup` CR with the `metadata.name` field.
. Specify the {brandname} cluster to backup with the `spec.cluster` field.
. Configure the persistent volume claim (PVC) that adds the backup archive to the persistent volume (PV) with the `spec.volume.storage` and `spec.volume.storage.storageClassName` fields.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/backup.yaml[]
----
+
. Optionally include `spec.resources` fields to specify which {brandname} resources you want to back up.
+
If you do not include any `spec.resources` fields, the `Backup` CR creates an archive that contains all {brandname} resources.
If you do specify `spec.resources` fields, the `Backup` CR creates an archive that contains those resources only.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/backup_resources.yaml[]
----
+
You can also use the `*` wildcard character as in the following example:
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/backup_resources_glob.yaml[]
----
+
. Apply your `Backup` CR.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} my-backup.yaml
----

.Verification

. Check that the `status.phase` field has a status of `Succeeded` in the `Backup` CR and that {brandname} logs have the following message:
+
[source,options="nowrap",subs=attributes+]
----
ISPN005044: Backup file created 'my-backup.zip'
----
+
. Run the following command to check that the backup is successfully created:
+
[source,options="nowrap",subs=attributes+]
----
$ {describe_backup}
----
