[id='configuring-sites-automatically_{context}']
= Configuring {ispn_operator} to manage cross-site connections

[role="_abstract"]
Configure {ispn_operator} to establish cross-site views with {brandname} clusters.

.Prerequisites

* Create secrets that contain service account tokens for each backup location.

.Procedure

. Create an `Infinispan` CR for each {brandname} cluster.
. Specify the name of the local site with `spec.service.sites.local.name`.
. Set the value of the `spec.service.sites.local.expose.type` field to either `NodePort` or `LoadBalancer`.
. Optionally configure ports with the following fields:
+
* `spec.service.sites.local.expose.nodePort` if you use `NodePort`.
* `spec.service.sites.local.expose.port` if you use `LoadBalancer`.
+
. Specify the number of nodes that can send RELAY messages with the `service.sites.local.maxRelayNodes` field.
+
You should configure all nodes in the cluster to send RELAY messages for optimal performance.
This allows all nodes to send replication requests to backup locations directly, rather than forwarding the requests to relay nodes.
+
. Provide the name, URL, and secret for each {brandname} cluster that acts as a backup location with `spec.service.sites.locations`.
. If {brandname} cluster names or namespaces at the remote site do not match the local site, specify those values with the `clusterName` and `namespace` fields.
+
The following are example `Infinispan` CR definitions for **LON** and **NYC**:
+
* **LON**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_lon.yaml[]
----
+
* **NYC**
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_nyc.yaml[]
----
+
[IMPORTANT]
====
Be sure to adjust logging categories in your `Infinispan` CR to decrease log levels for JGroups TCP and RELAY2 protocols.
This prevents a large number of log files from uses container storage.

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_logging.yaml[]
----
====
+
. Configure your `Infinispan` CRs with any other {datagridservice} resources and then apply the changes.
. Verify that {brandname} clusters form a cross-site view.
.. Retrieve the `Infinispan` CR.
+
[source,options="nowrap",subs=attributes+]
----
include::cmd_examples/get_infinispan.adoc[]
----
+
.. Check for the `type: CrossSiteViewFormed` condition.

.Next steps

If your clusters have formed a cross-site view, you can start adding backup
locations to caches.
