[id='enabling-client-certificate-authentication_{context}']
= Enabling client certificate authentication

[role="_abstract"]
To enable client certificate authentication, you configure {brandname} to use trust stores with either the `Validate` or `Authenticate` strategy.

.Procedure

. Set either `Validate` or `Authenticate` as the value for the `spec.security.endpointEncryption.clientCert` field in your `Infinispan` CR.
+
[NOTE]
====
The default value is `None`.
====
+
. Specify the secret that contains the client trust store with the `spec.security.endpointEncryption.clientCertSecretName` field.
+
By default {ispn_operator} expects a trust store secret named `<cluster-name>-client-cert-secret`.
+
[NOTE]
====
The secret must be unique to each `Infinispan` CR instance in the {k8s} cluster.
When you delete the `Infinispan` CR, {k8s} also automatically deletes the associated secret.
====
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/cert_auth_enabled.yaml[]
----
+
. Apply the changes.

.Next steps

Provide {ispn_operator} with a trust store that contains all client certificates.
Alternatively you can provide certificates in PEM format and let {brandname} generate a client trust store.
