[id='using_custom_tls-{context}']
= Adding TLS Certificates to Encryption Secrets
Add a PKCS12 keystore or TLS certificate/key pair to a secret and configure
{brandname} to use it for endpoint encryption.

.Procedure

. Create an encryption secret.
+
For example, to create `tls_secret.yaml` see one of the following:
+
* link:#ref_tls_cert_secret-security_endpoints[Certificate Secret]
* link:#ref_tls_cert_secret-security_endpoints[Keystore Secret]
+
. Add the encryption secret to your {openshiftshort} namespace.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} tls_secret.yaml
----
+
. Define a custom resource for the encryption secret.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml_annotated/cr_tls_secret.yaml[]
----
+
<1> encrypts traffic to and from {brandname} endpoints.
<2> configures {brandname} to use secrets that contain encryption certificates.
<3> names the encryption secret.
+
. Apply the custom resource with `{oc_apply_cr}`.
. Use `{oc_get_pods_w}` to watch the {ispn_operator} apply the custom resources.
