[id='upgrading-clusters-downtime_{context}']
= Upgrading {brandname} clusters with downtime

[role="_abstract"]
Upgrading {brandname} clusters with downtime results in service disruption but does not require any additional capacity.

.Prerequisites

* The {ispn_operator} version you have installed supports the {brandname} target version.
* If required, configure a persistent cache store to preserve your data during the upgrade.
+
[IMPORTANT]
====
At the start of the upgrade process {ispn_operator} shuts down your existing cluster.
This results in data loss if you do not configure a persistent cache store.
====

.Procedure

. Specify the {brandname} version number in the `spec.version` field.
. Ensure that `Shutdown` is set as the value for the `spec.upgrades.type` field, which is the default.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/upgrade_type_shutdown.yaml[]
----
+
. Apply your changes, if necessary.

When new {brandname} version becomes available, you must manually change the value in the `spec.version` field to trigger the upgrade.
