[id='exposing_routes-{context}']
= Exposing {brandname} Through Routes
//Community
ifdef::community[]
Use a {k8s} Ingress or an {openshiftshort} Route with passthrough encryption to
make {brandname} clusters available on the network.
endif::community[]
//Downstream
ifdef::downstream[]
Use an {openshiftshort} Route with passthrough encryption to make {brandname}
clusters available on the network.
endif::downstream[]

.Procedure

. Include `spec.expose` in your `Infinispan` CR.
. Specify `Route` as the service type with `spec.expose.type`.
. Optionally add a hostname with `spec.expose.host`.
+
[source,options="nowrap",subs=attributes+]
----
spec:
  ...
  expose:
    type: Route <1>
    host: www.example.org <2>
----
+
//Community
ifdef::community[]
<1> Exposes {brandname} on the network through a {k8s} Ingress or {openshiftshort} Route.
endif::community[]
//Downstream
ifdef::downstream[]
<1> Exposes {brandname} on the network through an {openshiftshort} Route.
endif::downstream[]
<2> Optionally specifies the hostname where {brandname} is exposed.
+
. Apply the changes.
. Verify that the route is available.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_get_routes}

NAME                 CLASS    HOSTS   ADDRESS   PORTS   AGE
{example_crd_name}   <none>   *                 443     73s
----

.Route ports
When you create a route, it exposes a port on the network that accepts client connections and redirects traffic to {brandname} services that listen on port `11222`.

The port where the route is available depends on whether you use encryption or not.

[%header,cols=2*]
|===
|Port
|Description

|`80`
|Encryption is disabled.

|`443`
|Encryption is enabled.
|===
