[id='backing-up-clusters_{context}']
= Backing up {brandname} clusters
Create a backup file that stores {brandname} cluster state to a persistent volume.

.Prerequisites

* Create an `Infinispan` CR of `spec.service.type: DataGrid`.
* Have some resources on your {brandname} cluster to back up.
Backups archive all resources that the Cache Manager controls, including caches, cache entries, cache templates, Protobuf schema, counters, scripts, and so on.

[IMPORTANT]
====
{brandname} backups do not provide snapshot isolation.
If a write operation occurs on a cache entry that the backup operation has already archived, that write might not be backed up.
To ensure that you archive the exact state of the cluster, make sure there are no active client connections to the cluster before you back it up.
====

.Procedure

. Create a `Backup` CR.
+
For example, create `my-backup.yaml` with the following:
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/backup.yaml[]
----
+
. Add the `spec.resources` field to back up certain resources only.
+
[source,options="nowrap",subs=attributes+]
----
include::yaml/backup_resources.yaml[]
----
+
. Apply your `Backup` CR.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} my-backup.yaml
----
+
A new pod joins the {brandname} cluster and creates the backup file.
When the operation is complete, the pod leaves the cluster and logs the following message:
+
[source,options="nowrap",subs=attributes+]
----
ISPN005044: Backup file created 'my-backup.zip'
----
+
The resulting backup file is stored in the `{backup_path}` directory.
+
. Run the following command to verify that the backup is successful:
+
[source,options="nowrap",subs=attributes+]
----
$ {describe_backup}
----
