[id='copying-code_{context}']
= Copying code artifacts
Before you can deploy custom code to {brandname} clusters, you need to add it to a persistent volume (PV).

This procedure explains how to use a temporary pod that mounts a persistent volume claim (PVC) that:

* Lets you add code artifacts to the PV (perform a write operation).
* Allows {brandname} pods to load code artifacts from the PV (perform a read operation).

To perform these read and write operations, you need certain PV access modes.
However, support for different PVC access modes is platform dependent.

It is beyond the scope of this document to provide instructions for creating PVCs with different platforms.
For simplicity, the following procedure shows a PVC with the `ReadWriteMany` access mode.

In some cases only the `ReadOnlyMany` or `ReadWriteOnce` access modes are available.
You can use a combination of those access modes by reclaiming and reusing PVCs with the same `spec.volumeName`.

[NOTE]
====
Using `ReadWriteOnce` access mode results in all {brandname} nodes in a cluster being scheduled on the same {k8s} node.
====

.Procedure

. Change to the namespace for your {brandname} cluster.
+
[source,options="nowrap",subs=attributes+]
----
$ {set_namespace}
----
+
. Create a PVC for your custom code artifacts, for example:
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/custom_code_pvc.yaml[]
----
+
. Apply your PVC.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} datagrid-libs.yaml
----
+
. Create a pod that mounts the PVC, for example:
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/custom_code_pod.yaml[]
----
+
. Add the pod to the {brandname} namespace and wait for it to be ready.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_apply_cr} datagrid-libs-pod.yaml
$ {oc_wait} --for=condition=ready --timeout=2m pod/datagrid-libs-pod
----
+
. Copy your code artifacts to the pod so that they are loaded into the PVC.
+
For example to copy code artifacts from a local `libs` directory, do the following:
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_copy} --no-preserve=true libs datagrid-libs-pod:/tmp/
----
+
. Delete the pod.
+
[source,options="nowrap",subs=attributes+]
----
$ {oc_delete_pod} datagrid-libs-pod
----

[role="_additional-resources"]
.Additional resources

* link:{link_os_storage}
* link:{link_k8s_storage}
* link:{link_k8s_access_modes}
ifdef::downstream[]
* link:https://access.redhat.com/solutions/4651451[How to manually reclaim and reuse OpenShift Persistent volumes that are "Released"] (Red Hat Knowledgebase)
endif::downstream[]
