[id='connecting-cli_{context}']
= Connecting to {brandname} clusters with remote shells

[role="_abstract"]
Start a remote shell session to {brandname} clusters and use the command line interface (CLI) to work with {brandname} resources and perform administrative operations.

.Prerequisites

* Have `kubectl-infinispan` on your `PATH`.
* Have valid {brandname} credentials.

.Procedure

. Run the [command]`infinispan shell` command to connect to your {brandname} cluster.
+
[source,bash,options="nowrap",subs=attributes+]
----
$ {kube_client} infinispan shell <cluster_name>
----
+
[NOTE]
====
If you have access to authentication secrets and there is only one {brandname} user the `kubectl-infinispan` plugin automatically detects your credentials and authenticates to {brandname}.
If your deployment has multiple {brandname} credentials, specify a user with the `--username` argument and enter the corresponding password when prompted.
====
+
. Perform CLI operations as required.
+
[TIP]
====
Press the tab key or use the [command]`--help` argument to view available options and help text.
====
+
. Use the [command]`quit` command to end the remote shell session.

[role="_additional-resources"]
.Additional resources
* link:{cli_docs}[Using the {brandname} Command Line Interface]
