[id='securing-cross-site-connections_{context}']
= Securing cross-site connections

[role="_abstract"]
Add keystores and trust stores so that {brandname} clusters can secure cross-site replication traffic.

You must add a keystore to use an {openshiftshort} `Route` as the expose type for cross-site replication.
Securing cross-site connections is optional if you use a `NodePort` or `LoadBalancer` as the expose type.

[NOTE]
====
Cross-site replication does not support the {k8s} CA service. You must provide your own certificates.
====

.Prerequisites

* Have a PKCS12 keystore that {brandname} can use to encrypt and decrypt RELAY messages.
+
You must provide a keystore for relay pods and router pods to secure cross-site connections. +
The keystore can be the same for relay pods and router pods or you can provide separate keystores for each. +
You can also use the same keystore for each {brandname} cluster or a unique keystore for each cluster.

* Have a PKCS12 trust store that contains part of the certificate chain or root CA certificate that verifies public certificates for {brandname} relay pods and router pods.

.Procedure

. Create cross-site encryption secrets.
.. Create keystore secrets.
.. Create trust store secrets.
. Modify the `Infinispan` CR for each {brandname} cluster to specify the secret name for the `encryption.transportKeyStore.secretName` and `encryption.routerKeyStore.secretName` fields.
. Configure any other fields to encrypt RELAY messages as required and then apply the changes.
+
[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/xsite_tls.yaml[]
----
