[id='storage_resources-{context}']
= Storage Resources
By default, {ispn_operator} allocates `1Gi` for storage for both
{cacheservice} and {datagridservice} nodes. You can configure storage resources
for {datagridservice} nodes but not {cacheservice} nodes.

[source,options="nowrap",subs=attributes+]
----
include::yaml/cr_container_storage.yaml[]
----

<1> Configures the storage size for {datagridservice} nodes.
<2> Defines whether storage is ephemeral or permanent. Set the value to `true` to use ephemeral storage, which means all data in storage is deleted when clusters shut down or restart. The default value is `false`, which means storage is permanent.
<3> Specifies the name of a StorageClass object to use for the persistent volume claim. If you include this field, you must specify an existing storage class as the value. If you do not include this field, the persistent volume claim uses the storage class that has the `storageclass.kubernetes.io/is-default-class` annotation set to `true`.

.Persistent Volume Claims

{ispn_operator} mounts persistent volumes at: +
`{pv_path}`

[NOTE]
====
Persistent volume claims use the `ReadWriteOnce (RWO)` access mode.
====
