[id='ref_upgrades-{context}']
= {ispn_operator} Upgrades
{ispn_operator} upgrades {brandname} when new versions become available.

To upgrade {brandname} clusters, {ispn_operator} checks the version of the
image for {brandname} nodes. If {ispn_operator} determines that a new
version of the image is available, it gracefully shuts down all nodes, applies
the new image, and then restarts the nodes.

//Community only
ifndef::productized[]
{ispn_operator} requires the Operator Lifecycle Manager to perform cluster
upgrades.
endif::productized[]

//Product only
ifdef::productized[]
On {openshift}, the Operator Lifecycle Manager (OLM) enables upgrades for
{ispn_operator}. When you install {ispn_operator}, you select either
**Automatic** or **Manual** updates with the **Approval Strategy**. This
determines how {ispn_operator} upgrades clusters. See the {openshiftshort}
documentation for more information.
endif::productized[]

.Reference

//Community only
ifndef::productized[]
* link:{link_olm}
* link:{link_olm_arch}
endif::productized[]
//Product only
ifdef::productized[]
* link:{link_os_olm}
* link:{link_os_olm_adding}
endif::productized[]
