[id='upgrades_{context}']
= {brandname} cluster upgrades

[role="_abstract"]
{ispn_operator} can automatically upgrade {brandname} clusters when new versions become available.
You can also perform upgrades manually if you prefer to control when they occur.

//Community Only
ifdef::community[]
[NOTE]
====
{ispn_operator} requires the Operator Lifecycle Manager to perform cluster upgrades.
====
endif::community[]

[discrete]
== Upgrade notifications

//Community Only
ifdef::community[]
If you upgrade {brandname} clusters manually and have upgraded the channel for your {ispn_operator} subscription from **2.0.x** to **2.1.x** you should apply the upgrade for the latest {brandname} 12.x version as soon as possible.
This upgrade avoids potential data loss that can occur in earlier versions with link:https://issues.redhat.com/browse/ISPN-13116[ISPN-13116].
endif::community[]
//Downstream only
ifdef::downstream[]
If you upgrade {brandname} clusters manually and have upgraded the channel for your {ispn_operator} subscription from **8.1.x** to **8.2.x** you should apply the upgrade for the latest {brandname} 8.2.x version as soon as possible to avoid potential data loss that can result from an issue in 8.2.0.
For more information, see link:{relnotes_openshift}[{ispn_operator} {ProductVersion} Release Notes].
endif::downstream[]
