[id='ref_xsite_crd_automatic-{context}']
= Resources for Automatic Cross-Site Connections

[source,options="nowrap",subs=attributes+]
----
include::yaml/cr_backup_site_automatic.yaml[]
----

//Community
ifdef::community[]
<1> Specifies {datagridservice}. {brandname} supports cross-site replication with {datagridservice} clusters only.
<2> Names the local site for a {brandname} cluster.
<3> Defines the externally exposed service.
* Use `NodePort` for local clusters on the same network.
* Use `LoadBalancer` for independent {openshiftshort} clusters.
<4> Provides connection information for all backup locations.
<5> Specifies a backup location that matches `.spec.service.sites.local.name`.
<6> Specifies a backup location.
* Use `kubernetes://` if the backup location is a Kubernetes instance.
* Use `openshift://` if the backup location is an {openshiftshort} cluster. You should specify the URL of the Kubernetes API.
* Use `infinispan+xsite://` if the backup location has a static hostname and port.
<7> Specifies the access secret for a site.
+
[NOTE]
====
This secret contains different authentication objects, depending on your
Kubernetes environment.
====
+
<8> Specifies the cluster name at the backup location if it is different to the cluster name at the local site.
<9> Specifies the namespace of the {brandname} cluster at the backup location if it does not match the namespace at the local site.
<10> Logs error messages for the JGroups TCP protocol.
<11> Logs error messages for the JGroups RELAY2 protocol.
endif::community[]

//Downstream
ifdef::downstream[]
<1> Specifies {datagridservice}. {brandname} supports cross-site replication with {datagridservice} clusters only.
<2> Names the local site for a {brandname} cluster.
<3> Specifies `LoadBalancer` as the service that handles communication between backup locations.
<4> Provides connection information for all backup locations.
<5> Specifies a backup location that matches `.spec.service.sites.local.name`.
<6> Specifies the URL of the {openshiftshort} API for the backup location.
<7> Specifies the secret that contains the service account token for the backup site.
<8> Specifies the cluster name at the backup location if it is different to the cluster name at the local site.
<9> Specifies the namespace of the {brandname} cluster at the backup location if it does not match the namespace at the local site.
<10> Logs error messages for the JGroups TCP protocol.
<11> Logs error messages for the JGroups RELAY2 protocol.
endif::downstream[]
