[id='ref_xsite_crd_manual-{context}']
= Resources for Manual Cross-Site Connections

[source,options="nowrap",subs=attributes+]
----
include::yaml/cr_backup_site_manual.yaml[]
----

<1> Specifies {datagridservice}. {brandname} supports cross-site replication with {datagridservice} clusters only.
<2> Names the local site for a {brandname} cluster.
//Community
ifdef::community[]
<3> Defines the externally exposed service.
* Use `NodePort` for local clusters on the same network.
* Use `LoadBalancer` for independent {openshiftshort} clusters.
endif::community[]
//Downstream
ifdef::downstream[]
<3> Specifies `LoadBalancer` as the service that handles communication between backup locations.
endif::downstream[]
<4> Provides connection information for all backup locations.
<5> Specifies a backup location that matches `.spec.service.sites.local.name`.
<6> Specifies the static URL for the backup location in the format of `infinispan+xsite://<hostname>:<port>`. The default port is `7900`.
<7> Logs error messages for the JGroups TCP protocol.
<8> Logs fatal messages for the JGroups RELAY2 protocol.
