[id='anti-affinity-strategies_{context}']
= Anti-affinity strategy configurations

[role="_abstract"]
Configure anti-affinity strategies in your `Infinispan` CR to control where {k8s} schedules {brandname} replica pods.

[%header,cols=2*]
|===
|Topology keys
|Description

|`topologyKey: "topology.kubernetes.io/zone"`
|Schedules {brandname} replica pods across multiple zones.

|`topologyKey: "kubernetes.io/hostname"`
|Schedules {brandname} replica pods on different {k8s} nodes.

|===

[discrete]
== Schedule pods on different {k8s} nodes

The following is the anti-affinity strategy that {ispn_operator} uses if you do not configure the `spec.scheduling.affinity` field in your `Infinispan` CR:

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/affinity_nodes_prefer.yaml[]
----

[discrete]
=== Requiring different nodes

In the following example, {k8s} does not schedule {brandname} pods if different nodes are not available:

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/affinity_nodes_require.yaml[]
----

[NOTE]
====
To ensure that you can schedule {brandname} replica pods on different {k8s} nodes, the number of {k8s} nodes available must be greater than the value of `spec.replicas`.
====

[discrete]
== Schedule pods across multiple {k8s} zones

The following example prefers multiple zones when scheduling pods but schedules {brandname} replica pods on different {k8s} nodes if it is not possible to schedule across zones:

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/affinity_zones_prefer.yaml[]
----

[discrete]
=== Requiring multiple zones

The following example uses the zone strategy only when scheduling {brandname} replica pods:

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml/affinity_zones_require.yaml[]
----

[discrete]
== Scheduling the Gossip Router

[role="_abstract"]
When cross-site replication is enabled, {ispn_operator} also deploys a Gossip Router pod. The `spec.scheduling.tolerations` and `spec.scheduling.priorityClassName` fields are applied to the Gossip Router pod in the same way as to {brandname} replica pods.

[NOTE]
====
Only the `nodeAffinity` rules configured in `spec.scheduling.affinity` are applied to the Gossip Router pod. `podAffinity`, `podAntiAffinity`, and `spec.scheduling.topologySpreadConstraints` are not propagated because the Gossip Router pod does not share the same labels as {brandname} replica pods, and because the Gossip Router runs as a single replica.
====
