[id='ref_xsite_crd_manually-{context}']
= Cross-Site Replication Resources

[source,options="nowrap",subs=attributes+]
----
include::yaml/cr_backup_site_manually.yaml[]
----

//Community
ifdef::community[]
<1> Specifies {datagridservice}. {brandname} supports cross-site replication with {datagridservice} clusters only.
<2> Names the local site for a {brandname} cluster.
<3> Defines the externally exposed service.
* Use `NodePort` for local clusters on the same network.
* Use `LoadBalancer` for independent {openshiftshort} clusters.
<4> Provides connection information for all backup locations.
<5> Specifies a backup location that matches `spec.service.sites.local.name`.
<6> Specifies the static URL for the backup location in the format of `infinispan+xsite://<hostname>:<port>`. The default port is `7900`.
<7> Logs error messages for the JGroups TCP protocol.
<8> Logs fatal messages for the JGroups RELAY2 protocol.
endif::community[]

//Downstream
ifdef::downstream[]
<1> Specifies {datagridservice}. {brandname} supports cross-site replication with {datagridservice} clusters only.
<2> Names the local site for a {brandname} cluster.
<3> Specifies `LoadBalancer` as the service that handles communication between backup locations.
<4> Provides connection information for all backup locations.
<5> Specifies a backup location that matches `spec.service.sites.local.name`.
<6> Specifies the static URL for the backup location in the format of `infinispan+xsite://<hostname>:<port>`. The default port is `7900`.
<7> Logs error messages for the JGroups TCP protocol.
<8> Logs fatal messages for the JGroups RELAY2 protocol.
endif::downstream[]
