[id='anti_affinity_configuration-{context}']
= Anti-Affinity Strategy Configurations
Configure anti-affinity strategies in your `Infinispan` CR to control where {k8s} schedules {brandname} replica pods.

[discrete]
== Schedule pods on different {k8s} nodes

The following is the anti-affinity strategy that {ispn_operator} uses if you do not configure the `spec.affinity` field in your `Infinispan` CR:

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml_annotated/affinity_nodes_prefer.yaml[]
----
<1> Sets the hostname strategy as most preferred.
<2> Schedules {brandname} replica pods on different {k8s} nodes.

.Requiring different nodes

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml_annotated/affinity_nodes_require.yaml[]
----
<1> {k8s} does not schedule {brandname} pods if there are no different nodes available.

[NOTE]
====
To ensure that you can schedule {brandname} replica pods on different {k8s} nodes, the number of {k8s} nodes available must be greater than the value of `spec.replicas`.
====

[discrete]
== Schedule pods across multiple {k8s} zones

The following example prefers multiple zones when scheduling pods:

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml_annotated/affinity_zones_prefer.yaml[]
----
<1> Sets the zone strategy as most preferred.
<2> Schedules {brandname} replica pods across multiple zones.
<3> Sets the hostname strategy as next preferred.
<4> Schedules {brandname} replica pods on different {k8s} nodes if it is not possible to schedule across zones.

.Requiring multiple zones

[source,yaml,options="nowrap",subs=attributes+]
----
include::yaml_annotated/affinity_zones_require.yaml[]
----
<1> Uses the zone strategy only when scheduling {brandname} replica pods.
