[id='encryption-service-ca_{context}']
= Encryption with {openshift} service certificates
{ispn_operator} automatically generates TLS certificates that are signed by the
{openshift} service CA. {ispn_operator} then stores the certificates and keys
in a secret so you can retrieve them and use with remote clients.

If the {openshift} service CA is available, {ispn_operator} adds the following `spec.security.endpointEncryption` configuration to the `Infinispan` CR:

[source,options="nowrap",subs=attributes+]
----
include::yaml/encryption_service_ca.yaml[]
----

[%header,cols=2*]
|===
|Field
|Description

|`spec.security.endpointEncryption.certServiceName`
|Specifies the service that provides TLS certificates.

|`spec.security.endpointEncryption.certSecretName`
|Specifies a secret with a service certificate and key in PEM format. Defaults to `<cluster_name>-cert-secret`.

|===

[NOTE]
====
Service certificates use the internal DNS name of the {brandname} cluster as the common name (CN), for example:

`Subject: CN = example-infinispan.mynamespace.svc`

For this reason, service certificates can be fully trusted only inside
{openshiftshort}. If you want to encrypt connections with clients running
outside {openshiftshort}, you should use custom TLS certificates.

Service certificates are valid for one year and are automatically replaced
before they expire.
====
