[id='default-cache-service-config_{context}']
= Default cache configuration

[role="_abstract"]
This topic describes default cache configuration for {cacheservice} pods.

[source,xml,options="nowrap",subs=attributes+]
----
include::xml/default-cache.xml[]
----

Default caches:

* Use synchronous distribution to store data across the cluster.
* Create two replicas of each entry on the cluster.
* Store cache entries as bytes in native memory (off-heap).
* Define the maximum size for the data container in bytes. {ispn_operator} calculates the maximum size when it creates pods.
* Evict cache entries to control the size of the data container. You can enable automatic scaling so that {ispn_operator} adds pods when memory usage increases instead of removing entries.
* Use a conflict resolution strategy that allows read and write operations for cache entries, even if segment owners are in different partitions.
* Specify a merge policy that removes entries from the cache when {brandname} detects conflicts.
