[id='ref_services-{context}']
= Services
The {ispn_operator} automatically creates services to route network traffic.
These services use the names that you give to your {brandname} clusters.

Internal services::
+
* Allow {brandname} nodes to discover each other and form clusters.
* Provide access to {brandname} endpoints from clients in the same {k8s} namespace.
+
[%header,cols=4*]
|===
| Service
| Port
| Protocol
| Description

| `${cluster_name}`
| `11222`
| TCP
| {brandname} endpoints

| `${cluster_name}-ping`
| `8888`
| TCP
| Cluster discovery

|===

External services::
Provide access to {brandname} endpoints from clients outside {k8s} or in different namespaces.
+
[NOTE]
====
You must expose external services with the {ispn_operator}. External services
are not available by default.
====
+
[%header,cols=4*]
|===
| Service
| Port
| Protocol
| Description

| `${cluster_name}-external`
| `11222`
| TCP
| {brandname} endpoints

|===

.Reference

link:#external_services[Making {brandname}
Available to External Traffic]
