---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infinispan-org-v1-infinispan
  failurePolicy: Fail
  name: minfinispan.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - infinispans
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infinispan-org-v2alpha1-backup
  failurePolicy: Fail
  name: mbackup.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infinispan-org-v2alpha1-cache
  failurePolicy: Fail
  name: mcache.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - caches
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-infinispan-org-v2alpha1-restore
  failurePolicy: Fail
  name: mrestore.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - restores
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infinispan-org-v1-infinispan
  failurePolicy: Fail
  name: vinfinispan.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - infinispans
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infinispan-org-v2alpha1-backup
  failurePolicy: Fail
  name: vbackup.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infinispan-org-v2alpha1-batch
  failurePolicy: Fail
  name: vbatch.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - batches
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infinispan-org-v2alpha1-cache
  failurePolicy: Fail
  name: vcache.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - caches
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infinispan-org-v2alpha1-restore
  failurePolicy: Fail
  name: vrestore.kb.io
  rules:
  - apiGroups:
    - infinispan.org
    apiVersions:
    - v2alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - restores
  sideEffects: None
