apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 2
  security:
    endpointEncryption:
            type: service
            certServiceName: service.beta.openshift.io
            certSecretName: tls-secret
