apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: mybatch
spec:
  cluster: {example_crd_name}
  config: |
    create counter --concurrency-level=1 --initial-value=5 --storage=VOLATILE --type=weak batch-counter

