apiVersion: v1
kind: ConfigMap
metadata:
   name: cluster-config
   namespace: {example_namespace}
data:
   infinispan-config.xml: >
     <infinispan>
       <!-- Custom configuration goes here. -->
     </infinispan>
