apiVersion: v1
kind: Pod
metadata:
  name: datagrid-libs-pod
spec:
  volumes:
    - name: lib-pv-storage
      persistentVolumeClaim:
        claimName: datagrid-libs
  securityContext:
    fsGroup: 1000600000
  containers:
    - name: lib-pv-container
      image: quay.io/infinispan/server:12.0
      volumeMounts:
        - mountPath: /tmp/libs
          name: lib-pv-storage
