apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 2
  dependencies:
    artifacts:
      - url: http://example.com:8080/path
        hash: d5db29cd03a2ed055086cef9c31c252b4587d6d0
        type: zip
  service:
    type: DataGrid
