apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 2
  dependencies:
    # Names the persistent volume claim that contains custom code.
    volumeClaimName: datagrid-libs
  service:
    type: DataGrid
