apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: Opaque
data:
  # Adds a base64-encoded TLS key.
  tls.key:  "LS0tLS1CRUdJTiBQUk ..."
  # Adds a base64-encoded TLS certificate.
  tls.crt: "LS0tLS1CRUdJTiBDRVl ..."
