apiVersion: v1
kind: ConfigMap
metadata:
  name: infinispan-operator-config
data:
  grafana.dashboard.namespace: {example_crd_name}
  grafana.dashboard.name: infinispan
  grafana.dashboard.monitoring.key: middleware
