apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  # Specifies a name for the ServiceMonitor.
  # The name must be unique to each {brandname} cluster.
  # For simplicity, add the "-monitor" suffix to the {brandname} cluster name.
  name: {example_crd_name}-monitor
  # Specifies a namespace for the ServiceMonitor.
  namespace: {example_namespace}
spec:
  endpoints:
    - port: infinispan-adm
      path: /metrics
      honorLabels: true
      basicAuth:
        username:
          key: username
          # Specifies the name of the authentication secret that holds credentials for the operator user.
          name: basic-auth
        password:
          key: password
          # Specifies the name of the authentication secret that holds credentials for the operator user.
          name: basic-auth
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
  namespaceSelector:
    # Specifies the namespace where your {brandname} cluster runs.
    matchNames:
      - {example_namespace}
  selector:
    matchLabels:
      app: infinispan-service
      # Specifies the name of your {brandname} cluster.
      clusterName: {example_crd_name}
