apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: datagrid-monitoring <1>
  namespace: infinispan-monitoring <2>
spec:
  endpoints:
    - targetPort: 11223 <3>
      path: /metrics <4>
      honorLabels: true
      basicAuth:
        username:
          key: username
          name: basic-auth <5>
        password:
          key: password
          name: basic-auth
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - infinispan <6>
  selector:
    matchLabels:
      app: infinispan-service
      clusterName: {example_crd_name} <7>
