apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name}
spec:
  replicas: 2
  version: <{brandname}_version>
  expose:
    type: LoadBalancer
  service:
    type: DataGrid
    sites:
      local:
        name: SiteA
        # ...
        encryption:
          protocol: TLSv1.3
          transportKeyStore:
            secretName: {ks_secret}
            alias: {alias}
            filename: {keystore}
          routerKeyStore:
            secretName: {ks_secret}
            alias: {alias}
            filename: {keystore}
          trustStore:
            secretName: {ts_secret}
            filename: {truststore}
      locations:
        # ...
