apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infinispans.cache.infinispan.org
spec:
  group: cache.infinispan.org
  names:
    kind: Infinispan
    listKind: InfinispanList
    plural: infinispans
    singular: infinispan
  scope: Namespaced
  version: v1alpha1
