= Infinispan Operator - API Documentation
:toc:               left

This document describes the types introduced by the Infinispan Operator to be consumed by users.


[[infinispan]]
## `Infinispan`

`Infinispan` defines a custom Infinispan resource.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `metadata`
| Standard object’s metadata
(https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#metadata[more info])
| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#objectmeta-v1-meta[metav1.ObjectMeta]
| false

| `spec`
| Specification of the desired behaviour of the Infinispan deployment
(https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status[more info])
| <<infinispanspec>>
| true

| `status`
| Most recent observed status of the Infinispan deployment. Read-only.
(https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status#spec-and-status[more info])
| <<infinispanstatus>>
| false

|
|=======================

[[infinispanspec]]
### `InfinispanSpec`

`InfinispanSpec` is a specification of the desired behavior of the Infinispan resource.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `image`
| Operator image
| string
| false
| `infinispan/server:latest`

| `replicas`
| Number of instances for a Infinispan resource. If this value is set to 0 the cluster
is gracefully shut down.
| int32
| true
|

| `profile`
| Profile in use. See <<infinispanprofiles,profiles>> for details.
| `Default` / `Performance` / `Development`
| false
| `Default`

| `service`
| Service specific configuration.
| <<infinispanservicespec>>
| false
|

| `security`
| Security configuration.
| <<infinispansecurityspec>>
| false
|

| `container`
| Per instance configuration.
| <<infinispancontainerspec>>
| false
|

| `logging`
| Logging categories
| []<<infinispanloggingcategoryspec>>
| false
|

| `expose`
| Expose Infinispan for external access over port 11222.
At the very least,
the user must indicate via `type` attribute how the
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#service-v1-core[Service]
is exposed.
`NodePort` is often used while testing locally,
while `LoadBalancer` is used in production-like environments where an external load-balancer is available.
| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#servicespec-v1-core[core/v1/ServiceSpec]
| false
| Infinispan not exposed externally.

|=======================


[[infinispanservicespec]]
#### `InfinispanServiceSpec`

`InfinispanServiceSpec` configures aspects related to the cache or datagrid service.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `type`
| Type of service
| `Cache` / `DataGrid`
| true
| `Cache`

| `evictionPolicy`
| Cache service eviction policy
| `Reject` / `Evict`
| false
| `Evict`

| `replicationFactor`
| Cache service replication factor
| int32
| false
| `1`

| `container`
| Service specific container configuration.
| <<infinispanservicecontainerspec>>
| false
|

| `sites`
| Cross-site configuration
| <<infinispansitesspec>>
| false
|

|=======================


[[infinispanservicecontainerspec]]
#### `InfinispanServiceContainerSpec`

`InfinispanServiceContainerSpec` defines service specific container configurations.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `storage`
| Storage per Infinispan container in the data grid service.
Defines as indicated
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage[here].
| string
| false
| `1Gi`

|=======================


[[infinispanprofiles]]

#### Profiles

[options="header,footer"]
|=======================
| Profile | Connector Authentication | Connector Encryption | Cluster Authentication | Cluster Encryption

| `Default`
| X
| X
| X
| X

| `Performance`
| X
| X
| X
|

| `Development`
|
|
|
|

|=======================


[[infinispansecurityspec]]
#### `InfinispanSecuritySpec`

`InfinispanSecuritySpec` defines Infinispan security settings.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `roles`
| Roles for interacting with Infinispan.
| []<<infinispanrolespec>>
| false
|

| `endpointSecretName`
| Secret containing identities allowed to interact with Infinispan.
The format of the metadata in the secret can be found <<identities,here>>.
| string
| false
|

| `endpointEncryption`
| Encryption configuration for client.
| EndpointEncryption
| false
|

|=======================

[[endpointencryption]]
#### `EndpointEncryption`

`EndpointEncryption` encryption configuration for client.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `type`
| Certificates provider type: `service` if the user wants to use a platform serving
certificates service. `secret` if the user provides a secret with certs inside
| `service`/`secret`
| true
|

| `certServiceName`
| Name of the serving certificates service. Only `service.beta.infinispan.io` is
currently supported
| string
| false
|

| `certSecretName`
| Name of the secret containing the certificates (both for service and secret type)
| string
| true
|

|=======================

[[infinispanrolespec]]
#### `InfinispanRoleSpec`

`InfinispanRoleSpec` defines Infinispan role definitions.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `name`
| Name of role.
| string
| true
|

| `permissions`
| List of permissions.
Valid values are defined
https://infinispan.org/docs/dev/titles/security/security.html#security_embedded_permissions[here].
| []string
| true
|

|=======================


[[infinispancontainerspec]]
#### `InfinispanContainerSpec`

`InfinispanContainerSpec` is a specification of the resource needed by the Infinispan container.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `extraJvmOpts`
| Extra Java opts to pass to Infinispan JVM
| string
| false
|

| `memory`
| Amount of memory required by the container
| string
| false
| 512Mi

| `cpu`
| Cpu to be allocated to the Infinispan container
| string
| false
| 0.5

|=======================


[[infinispanloggingspec]]
#### `InfinispanLoggingSpec`

`InfinispanLoggingSpec` configures logging.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `categories`
| Logging categories
| <<infinispanloggingcategoriesspec>>
| false
|

|=======================


[[infinispanloggingcategoriesspec]]
#### `InfinispanLoggingCategoriesSpec`

`InfinispanLoggingCategoriesSpec` configures logging categories.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `<category-name>`
| Logging category name, e.g. `org.infinispan`
| `error` / `warn` / `info` / `debug` / `trace`
| true
|

|=======================


[[infinispanprometheusspec]]
#### `InfinispanPrometheusSpec`

`InfinispanPrometheusSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `enabled`
| Enable prometheus.
| boolean
| false
| false

|=======================


[[infinispansitesspec]]
#### `InfinispanSitesSpec`

`InfinispanSpitesSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `local`
| Local site information.
| <<infinispanlocalsitespec>>
| true
|

| `locations`
| Site information for all local and remote locations.
| []<<infinispanlocationssitespec>>
| true
|

|=======================


[[infinispanlocalsitespec]]
#### `InfinispanLocalSiteSpec`

`InfinispanLocalSiteSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `name`
| Name of site.
| string
| true
|

| `expose`
| For sites to communicate with each other,
a dedicated externally exposed service needs to be configured.
This section configures details of such service.
The exposed service name will contain a `-site` suffix.
If the site service is defined as `NodePort` type,
it binds to port `7900` by default and uses port `32660` as `nodePort`.
| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#servicespec-v1-core[core/v1/ServiceSpec]
| true
|

|=======================


[[infinispanlocationssitespec]]
#### `InfinispanLocationsSiteSpec`

`InfinispanLocationsSiteSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `name`
| Name of remote location.
| string
| true
|

| `url`
| URL for remote location.
`xsite://` scheme denotes that the remote locatio is configured with static host:port combination.
`minikube://` scheme denotes that external location is a minikube instance and the setting are extracted from the remote Kubernetes host:port.
`openshift://` scheme denotes that site location settings are extracted from the remote OpenShift host:port.
| string
| true
|

| `secretName`
| Contains the secret details for accessing remote Kubernetes or OpenShift instances.
If the `url` starts with `minikube`,
the secret should contain `certificate-authority`, `client-certificate` and `client-key` entries.
A secret containing these certificates can be created using `kubectl create secret generic`,
passing individual files using `--from-file` parameters.
If the `url` starts with `openshift`,
the secret should contain a `token` entry for accessing that OpenShift cluster.
| string
| false
|

|=======================


[[infinispanstatus]]
### `InfinispanStatus`

`InfinispanStatus` is the most recent observed status of the `InfinispanSpec`. Read-only.

TODO: @Vittorio, update with your proposal

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `pods`
| Status of the pods.
| []<<podstatus>>
| true

|=======================


[[podstatus]]
#### `PodStatus`

`PodStatus` is the most recent observed status of a pod running `InfinispanSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `name`
| Name of the Pod.
| string
| true

| `podIP`
| IP address allocated to the pod.
| string
| true

|=======================


[[identies]]
#### `Identities`

`Identities` defines the identities configuration that's stored within a Secret.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `credentials`
| Credentials (username and password) based identities.
| []<<credentials>>
| true

| `certificates`
| Certificate (p12 format) based identities.
| []<<certificate>>
| true

| `oauth`
| Identities provided by OAuth servers.
| []<<oauth>>
| true

| `tokens`
| Token-based identities.
| []<<token>>
| true

|=======================


[[credentials]]
#### `Credentials`

`Credentials`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `username`
| Username.
| string
| false

| `password`
| Password.
| string
| true

| `roles`
| Roles of credentials
| []string
| false

|=======================


[[certificate]]
#### `Certificate`

`Certificate`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `p12`
| Certificate encoded in base 64 format.
| string
| true

| `roles`
| Roles of credentials
| []string
| false

|=======================


[[oauth]]
#### `OAuth`

`OAuth`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `clientId`
| TODO
| string
| true

| `clientSecret`
| TODO
| string
| true

| `introspectionUrl`
| TODO
| string
| true

|=======================


[[token]]
#### `Token`

`Token`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `token`
| Authentication token for an identity.
| string
| true

|=======================


## Full Cache Example

.full-cache-example.yaml
[source,yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: full-cache-example-infinispan
spec:
  image: infinispan/server:latest
  replicas: 4
  profile: Development
  service:
    type: Cache
    evictionPolicy: Reject
    replicationFactor: 3
  security:
    roles:
    - name: admin
      permissions:
      - ADMIN
    - name: developer
      permissions:
      - WRITE
    - name: collaborator
      permissions:
      - READ
    endpointSecretName: endpoint-identities
    endpointEncryption:
        type: secret
        certSecretName: tls-secret
  container:
    extraJvmOpts: "-XX:NativeMemoryTracking=summary"
    cpu: "2000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: trace
      org.jgroups: trace
  expose:
    type: LoadBalancer
----

.endpoint-identities.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-identities
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: connectusr
      password: connectpass
      roles:
      - admin
      - developer
      - collaborator
    certificates:
    - p12: "FQSmxHHvFvrhEfKIq15axg=="
      roles:
      - admin
    oauth:
    - clientId: infinispan-server
      clientSecret: 1fdca4ec-c416-47e0-867a-3d471af7050f
      introspectionUrl: "http://..."
----

.tls-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
type: Opaque
stringData:
  #alias and password for the provided keystore
    alias: server
    password: password
data:
  #Infinispan will use keystore.p12 if provided, otherwise
  #will use tls.key, tls.crt
    keystore.p12:  "Add here a base64 encoded PKCS12"
    tls.key:  "Add here a base64 TLS key"
    tls.crt: "Add here a base64 TLS cert"
----

## Full DataGrid Example

.full-datagrid-example.yaml
[source,yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: full-datagrid-example-infinispan
spec:
  image: infinispan/server:latest
  replicas: 6
  profile: Performance
  service:
    type: DataGrid
    container:
      storage: 2Gi
    sites:
      local:
        name: google
        expose:
          type: LoadBalancer
      locations:
      - name: google
        url: xsite://google.host:23456
      - name: azure
        url: openshift://api.azure.host:6443
        secretName: azure-identities
      - name: aws
        url: openshift://api.aws.host:6443
        secretName: aws-identities
  security:
    endpointSecretName: endpoint-identities
    endpointEncryption:
      type: service
      certServiceName: service.beta.openshift.io
      certSecretName: served-tls-secret
  container:
    extraJvmOpts: "-XX:NativeMemoryTracking=summary"
    cpu: "1000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: debug
      org.jgroups: debug
  expose:
    type: LoadBalancer
----

.azure-identities.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: azure-identities
type: Opaque
stringData:
  token: gl8xTESu_j_tzMQhpe_P-It6IcWFQUm94WsuR3VFkUw
----

.aws-identities.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: aws-identities
type: Opaque
stringData:
  token: LdqA1uM0e3wxhwOf0WRaP7Je3RdOjtrpai1jONQg7z0
----

## Minikube Example

Example highlighting settings that are commonly set in Minikube environments.

.minikube-example.yaml
[source,yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: minikube-example-infinispan
spec:
  replicas: 2
  profile: Development
  service:
    type: DataGrid
    sites:
      local:
        name: SiteA
        expose:
          type: NodePort
      locations:
      - name: SiteA
        url: minikube://192.168.99.147:8443
        secretName: site-secrets
      - name: SiteB
        url: minikube://192.168.99.148:8443
        secretName: site-secrets
  expose:
    type: NodePort
----

.site-b-secrets.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: site-b-secrets
type: Opaque
data:
  certificate-authority: <...>
  client-certificate: <...>
  client-key: <...>
----
