= Infinispan Operator - API Documentation
:toc:               left

This document describes the types introduced by the Infinispan Operator to be consumed by users.


[[infinispan]]
## `Infinispan`

`Infinispan` defines a custom Infinispan resource.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `metadata`
| Standard object’s metadata
(https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#metadata[more info])
| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#objectmeta-v1-meta[metav1.ObjectMeta]
| false

| `spec`
| Specification of the desired behaviour of the Infinispan deployment
(https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status[more info])
| <<infinispanspec>>
| true

| `status`
| Most recent observed status of the Infinispan deployment. Read-only.
(https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status#spec-and-status[more info])
| <<infinispanstatus>>
| false

|
|=======================

[[infinispanspec]]
### `InfinispanSpec`

`InfinispanSpec` is a specification of the desired behavior of the Infinispan resource.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `image`
| Operator image
| string
| false
| `jboss/infinispan-server:latest`

| `replicas`
| Number of instances for a Infinispan resource.
| int32
| true
|

| `profile`
| Profile in use. See <<infinispanprofiles,profiles>> for details.
| `Secured` / `Performance` / `Development`
| false
| `Secured`

| `cache`
| Cache configuration.
| <<infinispancachespec>>
| false
|

| `datagrid`
| Datagrid configuration.
| <<infinispandatagridspec>>
| false
|

| `connector`
| Connector configuration.
| <<infinispanconnectorspec>>
| false
|

| `container`
| Per instance configuration.
| <<infinispancontainerspec>>
| false
|

| `logging`
| Logging categories
| []<<infinispanloggingcategoryspec>>
| false
|

| `management`
| Management configuration.
| <<infinispanmgmtspec>>
| false
|

|=======================


[[infinispancachespec]]
#### `InfinispanCacheSpec`

`InfinispanCacheSpec` configures how Infinispan is used as a cache.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `evictionPolicy`
| Eviction policy
| `Reject` / `Evict`
| false
| `Evict`

| `replicationFactor`
| Replication factor
| int32
| false
| `1`

|=======================


[[infinispanprofiles]]

#### Profiles

[options="header,footer"]
|=======================
| Profile | Connector Authentication | Connector Encryption | Cluster Authentication | Cluster Encryption

| `Secured`
| X
| X
| X
| X

| `Performance`
| X
| X
| X
|

| `Development`
|
|
|
|

|=======================


[[infinispanconnectorspec]]
#### `InfinispanConnectorSpec`

`InfinispanConnectorSpec` defines how Infinispan is accessed.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `authentication`
| Authenticates access to Infinispan connectors.
| <<infinispanauthenticationspec>>
| false
|

|=======================


[[infinispancontainerspec]]
#### `InfinispanContainerSpec`

`InfinispanContainerSpec` is a specification of each Infinispan instance managed by `InfinispanSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `jvmOptionsAppend`
| Extra JVM options to pass to each `Infinispan` container.
| string
| false
|

| `cpu`
| CPU allocated for each Infinispan container.
Described as indicated
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu[here].
| string
| false
| `500m`

| `memory`
| Memory allocated for each Infinispan container.
Described as indicated
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory[here].
| string
| false
| `512Mi`

|=======================


[[infinispandatagridspec]]
#### `InfinispanDatagridSpec`

`InfinispanDatagridSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `storage`
| Storage per Infinispan container.
Described as indicated
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage[here].
| string
| false
| `1Gi`

| `datasources`
| Datasource list
| []<<infinispandatasourcespec>>
| false
|

| `sites`
| Cross-site configuration
| <<infinispansitesspec>>
| false
|

|=======================


[[infinispandatasourcespec]]
#### `InfinispanDatasourceSpec`

`InfinispanDatasourceSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `name`
| Name of datasource.
| string
| true
|

| `driver`
| Driver for datasource.
| string
| true
|

| `authentication`
| Authentication information for accessing datasource.
| <<infinispanauthenticationspec>>
| true
|

|=======================


[[infinispanloggingspec]]
#### `InfinispanLoggingSpec`

`InfinispanLoggingSpec` configures logging.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `categories`
| Logging categories
| <<infinispanloggingcategoriesspec>>
| false
|

|=======================


[[infinispanloggingcategoriesspec]]
#### `InfinispanLoggingCategoriesSpec`

`InfinispanLoggingCategoriesSpec` configures logging categories.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `<category-name>`
| Logging category name, e.g. `org.infinispan`
| `error` / `warn` / `info` / `debug` / `trace`
| true
|

|=======================


[[infinispanmgmtspec]]
#### `InfinispanManagementSpec`

`InfinispanManagementSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `prometheus`
| Prometheus configuration.
| <<infinispanprometheusspec>>
| false
|

| `authentication`
| Management authentication information.
| <<infinispanauthenticationspec>>
| false
|

|=======================


[[infinispanprometheusspec]]
#### `InfinispanPrometheusSpec`

`InfinispanPrometheusSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `enabled`
| Enable prometheus.
| boolean
| false
| false

|=======================


[[infinispansitesspec]]
#### `InfinispanSitesSpec`

`InfinispanSpitesSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `local`
| Local site information.
| <<infinispanlocalsitespec>>
| true
|

| `remotes`
| Remote site information.
| []<<infinispanremotesitespec>>
| true
|

|=======================


[[infinispanlocalsitespec]]
#### `InfinispanLocalSiteSpec`

`InfinispanLocalSiteSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `externalService`
| External service that is accessible from other sites.
| https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#service-v1-core[coreV1.Service]
| true
|

|=======================


[[infinispanremotesitespec]]
#### `InfinispanRemoteSiteSpec`

`InfinispanRemoteSiteSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `name`
| Name of remote site.
| string
| true
|

| `type`
| Type of remote site configuration.
| `Static` or `Dynamic`
| true
|

| `host`
| Remote site host name.
| string
| true
|

| `port`
| Remote site host port (only for `Static` type).
| int32
| false
|

| `authentication`
| Authentication information to connect to remote site (only for `Dynamic` type).
| <<infinispanauthenticationspec>>
| false
|

|=======================


[[infinispanauthenticationspec]]
##### `InfinispanAuthenticationSpec`

`InfinispanAuthenticationSpec` defines how authentication secrets are configured.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required | Default

| `type`
| Type of secret.
| `Credentials`, `Keystore` or `Token`
| true
|

| `secretName`
| Name of referenced secret.
| string
| true
|

|=======================

If type is `Credentials`, Secret` is expected to contain username and password credentials.
These would be defined in `stringData/username` and `stringData/password` fields respectively.

If type is `Keystore`, `Secret` is expected to contain base64 encoded data in `data/keystore.p12` field.
Optional keystore password would be located in `stringData/password` field.

If type is `Token`, `Secret` is expected to contain base64 encoded data in `stringData/token` field.


[[infinispanstatus]]
### `InfinispanStatus`

`InfinispanStatus` is the most recent observed status of the `InfinispanSpec`. Read-only.

TODO: @Vittorio, update with your proposal

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `pods`
| Status of the pods.
| []<<podstatus>>
| true

|=======================


[[podstatus]]
#### `PodStatus`

`PodStatus` is the most recent observed status of a pod running `InfinispanSpec`.

[options="header,footer"]
|=======================
| Field | Description | Scheme | Required

| `name`
| Name of the Pod.
| string
| true

| `podIP`
| IP address allocated to the pod.
| string
| true

|=======================

## Full Cache Example

.full-cache-example.yaml
[source,yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: full-cache-example-infinispan
spec:
  image: jboss/infinispan-server:latest
  replicas: 4
  profile: Development
  cache:
    evictionPolicy: Reject
    replicationFactor: 3
  connector:
    authentication:
      type: Credentials
      secretName: connect-secret
  container:
    jvmOptionsAppend: "-XX:NativeMemoryTracking=summary"
    cpu: "2000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: trace
      org.jgroups: trace
  management:
    prometheus:
      enabled: true
    authentication:
      type: Credentials
      secretName: mgmt-secret
----

.connect-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: connect-secret
type: Opaque
stringData:
  username: connectusr
  password: connectpass
----

.mgmt-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mgmt-secret
type: Opaque
stringData:
  username: mgmtusr
  password: mgmtpass
----


## Full DataGrid Example

.full-datagrid-example.yaml
[source,yaml]
----
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: full-datagrid-example-infinispan
spec:
  image: jboss/infinispan-server:latest
  replicas: 6
  profile: Performance
  datagrid:
    storage: 2Gi
    datasources:
    - name: test-pg
      driver: postgresql
      authentication:
        type: Credentials
        secretName: postgresql-secret
    - name: test-mysql
      driver: mysql
      authentication:
        type: Credentials
        secretName: mysql-secret
    sites:
      local:
        externalService:
          type: LoadBalancer
          ports:
            port: 12345
      remotes:
      - name: google
        type: Static
        host: google.host
        port: 23456
      - name: azure
        type: Dynamic
        host: azure.host
        authentication:
          type: Credentials
          secretName: azure-secret
      - name: aws
        type: Dynamic
        authentication:
          type: Token
          secretName: aws-secret
  connector:
    authentication:
      type: Keystore
      secretName: connect-auth-secret
  container:
    jvmOptionsAppend: "-XX:NativeMemoryTracking=summary"
    cpu: "1000m"
    memory: 1Gi
  logging:
    categories:
      org.infinispan: debug
      org.jgroups: debug
  management:
    prometheus:
      enabled: true
    authentication:
      type: Credentials
      secretName: mgmt-secret
----

.connect-auth-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: connect-auth-secret
type: Opaque
data:
  keystore.p12: "FQSmxHHvFvrhEfKIq15axg=="
----

.postgresql-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  username: pgusr
  password: pgpass
----

.mysql-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  username: myusr
  password: mypass
----

.mgmt-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mgmt-secret
type: Opaque
stringData:
  username: mgmtusr
  password: mgmtpass
----

.azure-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  username: azusr
  password: azpass
----

.aws-secret.yaml
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
  token: "jd1r/deZpYmY/mpvofUKWQ=="
----
