// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/infinispan/v1alpha1.Cache":       schema_pkg_apis_infinispan_v1alpha1_Cache(ref),
		"./pkg/apis/infinispan/v1alpha1.CacheSpec":   schema_pkg_apis_infinispan_v1alpha1_CacheSpec(ref),
		"./pkg/apis/infinispan/v1alpha1.CacheStatus": schema_pkg_apis_infinispan_v1alpha1_CacheStatus(ref),
	}
}

func schema_pkg_apis_infinispan_v1alpha1_Cache(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Cache is the Schema for the caches API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/infinispan/v1alpha1.CacheSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/infinispan/v1alpha1.CacheStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/infinispan/v1alpha1.CacheSpec", "./pkg/apis/infinispan/v1alpha1.CacheStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_infinispan_v1alpha1_CacheSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CacheSpec defines the desired state of Cache",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"infinispanSelector": {
						SchemaProps: spec.SchemaProps{
							Description: "Selector for looking up Infinispan Custom Resources.",
							Ref:         ref("k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"),
						},
					},
					"cacheConfigurationSpec": {
						SchemaProps: spec.SchemaProps{
							Description: "A user-provided Cache configuration.",
							Ref:         ref("./pkg/apis/infinispan/v1alpha1.CacheConfigurationSpec"),
						},
					},
				},
				Required: []string{"cacheConfigurationSpec"},
			},
		},
		Dependencies: []string{
			"./pkg/apis/infinispan/v1alpha1.CacheConfigurationSpec", "k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"},
	}
}

func schema_pkg_apis_infinispan_v1alpha1_CacheStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CacheStatus defines the observed state of Cache",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"conditions": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-patch-merge-key": "type",
								"x-kubernetes-patch-strategy":  "merge",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "Represents the latest available observations of a statefulset's current state.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("./pkg/apis/infinispan/v1alpha1.CacheCondition"),
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/infinispan/v1alpha1.CacheCondition"},
	}
}
