apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  connector-username: connectorusr
  connector-password: connectorpass
  management-username: managementusr
  management-password: managementpass
