apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  size: 2
  image: jboss/infinispan-server:latest
  connector:
    authentication:
      secret:
        type: Credentials
        secretName: conn-auth-secret
  management:
    authentication:
      secret:
        type: Credentials
        secretName: mngt-auth-secret
