apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 1
  service:
    type: DataGrid
    container:
      storage: 1Gi
      storageClassName: local-storage
