package server

import (
	"testing"

	"github.com/blang/semver"
	"github.com/infinispan/infinispan-operator/pkg/infinispan/version"
	"github.com/stretchr/testify/assert"
)

func TestGenerateAndGenerateZeroCapacity(t *testing.T) {
	baseCfg_expected := "<infinispan\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n    xsi:schemaLocation=\"urn:infinispan:config:15.1 https://infinispan.org/schemas/infinispan-config-15.1.xsd\n                        urn:infinispan:server:15.1 https://infinispan.org/schemas/infinispan-server-15.1.xsd\"\n    xmlns=\"urn:infinispan:config:15.1\"\n    xmlns:server=\"urn:infinispan:server:15.1\">\n\n<cache-container name=\"default\" statistics=\"true\">\n    <global-state unclean-shutdown-action=\"IGNORE\" />\n    \n    <security>\n        <authorization group-only-mapping=\"false\">\n            \n            <cluster-role-mapper />\n            \n            \n        </authorization>\n    </security>\n    \n    <transport cluster=\"${infinispan.cluster.name:}\" node-name=\"${infinispan.node.name:}\" stack=\"image-tcp\"    \n    />\n</cache-container>\n<server xmlns=\"urn:infinispan:server:15.1\">\n    <socket-bindings default-interface=\"public\" port-offset=\"${infinispan.socket.binding.port-offset:0}\">\n        <socket-binding name=\"default\" port=\"${infinispan.bind.port:11222}\"/>\n    </socket-bindings>\n    <security>\n        \n        \n        <security-realms>\n            <security-realm name=\"default\">\n                <server-identities>\n\t\t\t\t\n                </server-identities>\n                \n            </security-realm>\n            \n        </security-realms>\n    </security>\n    <endpoints>\n        <endpoint socket-binding=\"default\" security-realm=\"default\" require-ssl-client-auth=\"true\" />\n    </endpoints>\n</server>\n</infinispan>\n"
	adminCfg_expected := "<infinispan\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n    xsi:schemaLocation=\"urn:infinispan:config:15.1 https://infinispan.org/schemas/infinispan-config-15.1.xsd\n                        urn:infinispan:server:15.1 https://infinispan.org/schemas/infinispan-server-15.1.xsd\n                        urn:org:jgroups http://www.jgroups.org/schema/jgroups-5.5.xsd\"\n    xmlns=\"urn:infinispan:config:15.1\"\n    xmlns:server=\"urn:infinispan:server:15.1\">\n\n<jgroups>\n    \n    <stack name=\"image-tcp\" extends=\"kubernetes\">\n        <!-- overwrite diagnostics-->\n        <TCP diag.enabled=\"${jgroups.diag.enabled:false}\" stack.combine=\"COMBINE\" />\n        <!-- overwrite DNS query (only required attribute) -->\n        <dns.DNS_PING dns_query=\"${jgroups.dns.query:-ping..svc.cluster.local}\" stack.combine=\"COMBINE\" />\n    </stack>\n</jgroups>\n<server xmlns=\"urn:infinispan:server:15.1\">\n    <interfaces>\n        <interface name=\"public\">\n            <inet-address value=\"${infinispan.bind.address}\"/>\n        </interface>\n    </interfaces>\n    <socket-bindings default-interface=\"public\" port-offset=\"${infinispan.socket.binding.port-offset:0}\">\n        <socket-binding name=\"admin\" port=\"11223\"/>\n    </socket-bindings>\n    <security>\n        <security-realms>\n            <security-realm name=\"admin\">\n                <properties-realm groups-attribute=\"Roles\">\n                    <user-properties path=\"cli-admin-users.properties\" relative-to=\"infinispan.server.config.path\"/>\n                    <group-properties path=\"cli-admin-groups.properties\" relative-to=\"infinispan.server.config.path\"/>\n                </properties-realm>\n            </security-realm>\n        </security-realms>\n    </security>\n    <endpoints security-realm=\"admin\">\n        <endpoint socket-binding=\"admin\" security-realm=\"admin\">\n            <rest-connector>\n                <authentication mechanisms=\"BASIC DIGEST\"/>\n            </rest-connector>\n            <hotrod-connector />\n        </endpoint>\n    </endpoints>\n</server>\n</infinispan>\n"
	zeroCfg_expected := "<infinispan\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n    xsi:schemaLocation=\"urn:infinispan:config:15.1 https://infinispan.org/schemas/infinispan-config-15.1.xsd\n                        urn:infinispan:server:15.1 https://infinispan.org/schemas/infinispan-server-15.1.xsd\"\n    xmlns=\"urn:infinispan:config:15.1\"\n    xmlns:server=\"urn:infinispan:server:15.1\">\n\n<jgroups>\n    \n    <stack name=\"image-tcp\" extends=\"kubernetes\">\n        <!-- overwrite diagnostics-->\n        <TCP diag.enabled=\"${jgroups.diag.enabled:false}\" stack.combine=\"COMBINE\" />\n        <!-- overwrite DNS query (only required attribute) -->\n        <dns.DNS_PING dns_query=\"${jgroups.dns.query:-ping..svc.cluster.local}\" stack.combine=\"COMBINE\" />\n    </stack>\n</jgroups>\n<cache-container name=\"default\" statistics=\"true\" zero-capacity-node=\"true\">\n    \n    <security>\n        <authorization>\n            \n            <cluster-role-mapper />\n            \n            \n        </authorization>\n    </security>\n    \n    <transport cluster=\"${infinispan.cluster.name:}\" node-name=\"${infinispan.node.name:}\" stack=\"image-tcp\"\n     />\n</cache-container>\n<server xmlns=\"urn:infinispan:server:15.1\">\n    <interfaces>\n        <interface name=\"public\">\n            <inet-address value=\"${infinispan.bind.address}\"/>\n        </interface>\n    </interfaces>\n    <socket-bindings default-interface=\"public\" port-offset=\"${infinispan.socket.binding.port-offset:0}\">\n        <socket-binding name=\"admin\" port=\"11223\"/>\n    </socket-bindings>\n    <security>\n        <security-realms>\n            <security-realm name=\"admin\">\n                <properties-realm groups-attribute=\"Roles\">\n                    <user-properties path=\"cli-admin-users.properties\" relative-to=\"infinispan.server.config.path\"/>\n                    <group-properties path=\"cli-admin-groups.properties\" relative-to=\"infinispan.server.config.path\"/>\n                </properties-realm>\n            </security-realm>\n            \n        </security-realms>\n    </security>\n    <endpoints>\n        <endpoint socket-binding=\"admin\" security-realm=\"admin\">\n            <rest-connector>\n                <authentication mechanisms=\"BASIC DIGEST\"/>\n            </rest-connector>\n            <hotrod-connector />\n        </endpoint>\n    </endpoints>\n</server>\n</infinispan>\n"

	ispn := Infinispan{Authorization: &Authorization{Enabled: true}}
	spec := Spec{Infinispan: ispn}
	vers := semver.Version{Major: 15, Minor: 1, Patch: 25}
	ope := version.Operand{UpstreamVersion: &vers}

	baseCfg, adminCfg, err := Generate(ope, &spec)
	assert.Equal(t, baseCfg, baseCfg_expected)
	assert.Equal(t, adminCfg, adminCfg_expected)
	assert.Nil(t, err)

	zeroCfg, err := GenerateZeroCapacity(ope, &spec)
	assert.Equal(t, zeroCfg, zeroCfg_expected)
	assert.Nil(t, err)
}
