# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infinispan.org_infinispans.yaml
- bases/infinispan.org_backups.yaml
- bases/infinispan.org_restores.yaml
- bases/infinispan.org_batches.yaml
- bases/infinispan.org_caches.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
