apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: infinispan-operator.v9.9.9
  namespace: placeholder
  annotations:
    tectonic-visibility: ocs
    capabilities: Full Lifecycle
    categories: "Database"
    repository: https://github.com/infinispan/infinispan-operator
    alm-examples: |
      [
        {
          "apiVersion": "infinispan.org/v1",
          "kind": "Infinispan",
          "metadata": {
            "name": "example-infinispan"
          },
          "spec": {
            "replicas": 1
          }
        },
        {
          "apiVersion": "infinispan.org/v2alpha1",
          "kind": "Cache",
          "metadata": {
            "name": "example-cache"
          },
          "spec": {
            "adminAuth": {
              "secretName": "basic-auth"
            },
            "clusterName": "example-infinispan",
            "name": "mycache"
          }
        }
      ]
    description: Create and manage Infinispan clusters.
    containerImage: quay.io/infinispan/operator:2.0.x
    createdAt: 2000-01-01T12:00:00Z
    support: Infinispan
    certified: "false"
spec:
  displayName: Infinispan
  description: |
    Infinispan is a distributed, in-memory data store that increases application performance and delivers open-source capabilities to handle demanding use cases.

    ### Core Capabilities
    * **Schemaless data structure:** Store different objects as key-value pairs.
    * **Grid-based data storage:** Distribute and replicate data across clusters.
    * **Elastic scaling:** Dynamically adjust the number of nodes to meet demand without service disruption.
    * **Data interoperability:** Store, retrieve, and query data in the grid from different endpoints.
    * **High availability:** Always have access to your data.

    ### Infinispan Operator Features
    * Operational intelligence that simplifies Infinispan cluster deployment.
    * REST and Hot Rod endpoints available at port `11222`.
    * Cache service for a high-performance, ephemeral data store.
    * Data Grid service for a fully configurable Infinispan cluster.
    * Default application user: `developer`. Infinispan Operator generates credentials in an authentication secret at startup.
    * Infinispan pods request `0.25` (limit `0.50`) CPUs, 512MiB of memory and 1Gi of ReadWriteOnce persistent storage. Infinispan Operator lets you adjust resource allocation to suit your requirements.
  keywords: ['infinispan', 'key value', 'database', 'datagrid', 'open source']
  version: 9.9.9
  minKubeVersion: 1.11.0
  maturity: alpha
  maintainers:
    - name: Infinispan Community
      email: infinispan-dev@lists.jboss.org
  provider:
    name: Infinispan
  replaces: infinispan-operator.v9.9.8
  relatedImages:
    - name: infinispan-server
      image: quay.io/infinispan/server:11.0
  labels:
    operated-by: infinispan-operator
  selector:
    matchLabels:
      operated-by: infinispan-operator
  links:
    - name: Blog
      url: https://blog.infinispan.org/
    - name: Documentation
      url: https://infinispan.org/
    - name: Quickstart
      url: https://github.com/infinispan/infinispan-simple-tutorials/tree/master/operator
    - name: Operator Source Code
      url: https://github.com/infinispan/infinispan-operator

  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAACxAAAAsQHGLUmNAAAEOklEQVR4nO1bTUhUURQ+ZSioGAyNTFAmNBCjUEHSShRaTRs3tWlR61q3KciVC1e1rV3QOjduciUo0iIUpqARYQI1QVGZSHRASYrv8e7wmnz33vfmnjPPZj54zCjv3nfvd8/fO+fMmQdvP/6mJsbZZt480CIgAWtoKFoEJGANDYU1AVdSXTSQ6aHO9nOJ3QzWhjVirbaw3s2j2/2Uy/RU/97dP6S18gEVt/a8C98loQ5EbfhCd0f16ctbezQx89VqNbGPEw/EdasvVSVkrrRD86Vt2tk/ZKEi3d1BI9leGs2m/9pwPXAmz1jQvZuXvGu+tENThe/OiEh7c1+mkWzayXxBsCg0FoprqrBBH4qbVDn6FWse6PTdgYseqVxgtWhYOMT15exKZBsBvX5655ozUQ8DuxvEBibHrkcSX9yLMdybB8TigMfDWc+TmIB7cK8UYr0NKteDT+UFbAED+WahFEpSVEO3tF6uumF8RkUsG6B8PwwcDBX0HMbKRmSxQSwWY2v/b7t5uFyMh9uNa2AVnOYD4KpARGd7m/HeV7MrtLhe9r5Dkl7kB41jKkfH3sbhYl3BqQ3Awp5Pf7ay+BB3FVaDOBMwJ+Z2uXnAuRFE8DMxU/R0XQdIyZPhq94dpk1hLszJEWGyeAHoJQydiQQYUIg/7MlyiAFTRrNeXQ8DqxvEwsM2pqBc3klSgLFhHsMV2OMARIEwXmGA5xjqS/0jBRiDsdxgJ0Cpgw7wHMBcabt6F6fYByESCcLd6VQBeQa88S2u//BOHvcqF8kNsVDYZOmhBjjx5a2fzl2dDmIEmLJGQ35I/b6wESukjQvRpKjOLap0m3RqTZQAk15HSWa6gigBiOR0LrHL4h3CNcTrAjoRz2XOi64FECeAK2McFy0CErCGhiJRBKQFkqC1aBEg/UCdF/jv4wAyGEFkiaSlIFESQIF3AimIEqBEXPdqzFEA1UGMAOT+7vtFTt07gSq4SEGMAKS+VahreimySZO7gggB0Ouc117T5ok4DKEpQyRlC9gJQPEjWOwczfZ6n7WlsVoECyecYCcANf5gqSzn9/VADXYNLhFjTzUBOMXcCQZN6bgpW4yx3KVyFgKU2Ie5NCUFyP0tGQwi5uBUB+cEIJIbzw8Y/bmSgtcL37RZIvJJwJwcUaJTArCpybEbVjG9Sn3bFE7Ijw8wt2sXWXd/QNQGCfJ1vzZDjPEPLVpoKAkNEk3ZIjOeHzzRokfBTHGT3n1aDR2h6oF5v1ZoAxxA7SFEaZUVC4WxOd3mFXAPd0k8CPZQC/oatVESarJWrog0SrISUE+rLAh7Nv3ldLbKumqWBnGYBx3oiW+W5myXx3ywCyAjMe3yjfjBBIgACbh0P5iIAus4AA9B8XK1XBFpXYkDBGX9qU46ODq2PhBrCZCu28cBDiZqMNQqjSVgDQ1Fi4AErKGhaG4CiOgPK6Ej+g5fAyMAAAAASUVORK5CYII=
      mediatype: image/png

  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: true
    - type: AllNamespaces
      supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: infinispan-operator
          rules:
          - apiGroups:
              - ""
            resources:
              - pods
              - services
              - services/finalizers
              - endpoints
              - persistentvolumeclaims
              - events
              - configmaps
              - secrets
            verbs:
              - '*'
          - apiGroups:
              - ""
            resources:
              - pods/exec
            verbs:
              - create
          - apiGroups:
              - ""
            resources:
              - namespaces
            verbs:
              - get
          - apiGroups:
              - apps
            resources:
              - deployments
              - deployments/finalizers
              - daemonsets
              - replicasets
              - statefulsets
              - statefulsets/finalizers
            verbs:
              - '*'
          - apiGroups:
              - route.openshift.io
            resources:
              - routes
              - routes/custom-host
            verbs:
              - '*'
          - apiGroups:
              - networking.k8s.io
            resources:
              - ingresses
            verbs:
              - '*'
          - apiGroups:
              - monitoring.coreos.com
            resources:
              - servicemonitors
            verbs:
              - get
              - create
          - apiGroups:
              - infinispan.org
            resources:
              - '*'
            verbs:
              - '*'
      clusterPermissions:
        - serviceAccountName: infinispan-operator
          rules:
          - apiGroups:
              - ""
            resources:
              - nodes
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - apiextensions.k8s.io
            resources:
              - customresourcedefinitions
              - customresourcedefinitions/status
            verbs:
              - get
              - list
      deployments:
        - name: infinispan-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: infinispan-operator
            template:
              metadata:
                name: infinispan-operator
                labels:
                  name: infinispan-operator
              spec:
                serviceAccountName: infinispan-operator
                containers:
                  - name: infinispan-operator
                    command:
                      - infinispan-operator
                    image: quay.io/infinispan/operator:2.0.x
                    ports:
                      - containerPort: 60000
                        name: metrics
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "infinispan-operator"
                      - name: DEFAULT_IMAGE
                        value: "quay.io/infinispan/server:11.0"
  customresourcedefinitions:
    owned:
      - description: Cache is the Schema for the caches API
        kind: Cache
        displayName: Infinispan Cache
        name: caches.infinispan.org
        version: v2alpha1
      - name: infinispans.infinispan.org
        version: v1
        kind: Infinispan
        displayName: Infinispan Cluster
        description: An Infinispan cluster instance.
        resources:
          - kind: ConfigMap
            version: v1
          - kind: Secret
            version: v1
          - kind: Service
            version: v1
          - kind: Pod
            version: v1
        specDescriptors:
          - description: Sets the number of nodes in the cluster.
            displayName: Replicas
            path: replicas
          - description: Sets an image to bootstrap the Infinispan nodes.
            displayName: Image
            path: image
          - description: Sets the CPU limits for each Infinispan node.
            displayName: CPU
            path: container.cpu
          - description: Sets the memory limits for each Infinispan node.
            displayName: Memory
            path: container.memory
          - description: Appends JVM options to each Infinispan node.
            displayName: Extra JVM Options
            path: container.extraJvmOpts
          - description: Name of the secret that contains auth info.
            displayName: Endpoint Secret Name
            path: security.endpointSecretName
          - description: Select how encryption certificates are provided [Secret,Service].
            displayName: Endpoint Encryption Type
            path: security.endpointEncryption.type
          - description: Platform service that serves certificates (openshift.io/service-cert is supported).
            displayName: Serving Certs Service Name
            path: security.endpointEncryption.certServiceName
          - description: Name of the secret that contains certificates.
            displayName: Certificates Secret Name
            path: security.endpointEncryption.certSecretName
          - description: Select service type provided [Cache,DataGrid].
            displayName: Service Type
            path: service.type
          - description: Local Infinispan node storage capacity (DataGrid service only).
            displayName: Local Storage Capacity
            path: service.container.storage
          - description: Name of local site (DataGrid service only).
            displayName: Name Of Local Site
            path: service.sites.local.name
          - description: Kubernetes service type for cross-site communications [LoadBalancer,NodePort] (DataGrid service only).
            displayName: Kubernetes Service Type For Cross-Site Network
            path: service.sites.local.expose.type
          - description: Name of one of the sites (DataGrid service only)
            displayName: Name Of Site
            path: service.sites.locations[0].name
          - description: Site URL for communicating with site (DataGrid service only). Prefixed with minikube:// for Minikube sites, and openshift:// for OpenShift sites.
            displayName: Site URL
            path: service.sites.locations[0].url
          - description: Secret name containing credentials to talk to site (DataGrid service only).
            displayName: Secret For Site
            path: service.sites.locations[0].secretName
          - description: Defines logging categories and log levels.
            displayName: Logging Categories
            path: logging.categories
          - description: Externally exposed Kubernetes service type.
            displayName: Exposed Kubernetes Service Type
            path: expose.type
        statusDescriptors:
        - description: Type of condition.
          displayName: Condition Type
          path: conditions[0].type
        - description: Status of condition.
          displayName: Condition Status
          path: conditions[0].status
        - description: Message of condition.
          displayName: Condition Message
          path: conditions[0].message
