apiVersion: infinispan.org/v2alpha1
kind: Schema
metadata:
  name: person-schema
spec:
  clusterName: example-infinispan
  name: person.proto
  schema: |
    package org.infinispan;

    message Person {
        string name = 1;
        int32 age = 2;
        string email = 3;
    }
