apiVersion: infinispan.org/v2alpha1
kind: Batch
metadata:
  name: example-batch-inline
spec:
  cluster: example-infinispan
  config: |
    create counter --concurrency-level=1 --initial-value=5 --storage=VOLATILE --type=weak batch-counter
