apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: {example_crd_name} <1>
spec:
  replicas: 6 <2>
  service:
    type: DataGrid <3>
    container:
      storage: 2Gi <4>
    sites: <5>
      local:
        expose:
          type: LoadBalancer
      locations:
      - name: azure
        url: openshift://api.azure.host:6443
        secretName: azure-identities
      - name: aws
        url: openshift://api.aws.host:6443
        secretName: aws-identities
  security:
    endpointSecretName: endpoint-identities <6>
    endpointEncryption: <7>
        type: secret
        certSecretName: tls-secret
  container: <8>
    extraJvmOpts: "-XX:NativeMemoryTracking=summary"
    cpu: "1000m"
    memory: 1Gi
  logging: <9>
    categories:
      org.infinispan: debug
      org.jgroups: debug
  expose: <10>
    type: LoadBalancer
