apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: datagrid-monitoring <1>
  namespace: infinispan-monitoring <2>
spec:
  endpoints:
    - basicAuth:
        username:
          key: username
          name: basic-auth <3>
        password:
          key: password
          name: basic-auth <4>
      interval: 30s
      scheme: https <5>
      tlsConfig:
        insecureSkipVerify: true
        serverName: certificate-CN <6>
  namespaceSelector:
    matchNames:
      - infinispan <7>
  selector:
    matchLabels:
      app: infinispan-service
      clusterName: cluster-name <8>
