// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapConfig) DeepCopyInto(out *ConfigMapConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapConfig.
func (in *ConfigMapConfig) DeepCopy() *ConfigMapConfig {
	if in == nil {
		return nil
	}
	out := new(ConfigMapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Infinispan) DeepCopyInto(out *Infinispan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Config = in.Config
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Infinispan.
func (in *Infinispan) DeepCopy() *Infinispan {
	if in == nil {
		return nil
	}
	out := new(Infinispan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Infinispan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanAuthInfo) DeepCopyInto(out *InfinispanAuthInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanAuthInfo.
func (in *InfinispanAuthInfo) DeepCopy() *InfinispanAuthInfo {
	if in == nil {
		return nil
	}
	out := new(InfinispanAuthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanConfig) DeepCopyInto(out *InfinispanConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanConfig.
func (in *InfinispanConfig) DeepCopy() *InfinispanConfig {
	if in == nil {
		return nil
	}
	out := new(InfinispanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanConnectorInfo) DeepCopyInto(out *InfinispanConnectorInfo) {
	*out = *in
	out.Authentication = in.Authentication
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanConnectorInfo.
func (in *InfinispanConnectorInfo) DeepCopy() *InfinispanConnectorInfo {
	if in == nil {
		return nil
	}
	out := new(InfinispanConnectorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanContainerSpec) DeepCopyInto(out *InfinispanContainerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanContainerSpec.
func (in *InfinispanContainerSpec) DeepCopy() *InfinispanContainerSpec {
	if in == nil {
		return nil
	}
	out := new(InfinispanContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanList) DeepCopyInto(out *InfinispanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Infinispan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanList.
func (in *InfinispanList) DeepCopy() *InfinispanList {
	if in == nil {
		return nil
	}
	out := new(InfinispanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfinispanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanManagementInfo) DeepCopyInto(out *InfinispanManagementInfo) {
	*out = *in
	out.Authentication = in.Authentication
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanManagementInfo.
func (in *InfinispanManagementInfo) DeepCopy() *InfinispanManagementInfo {
	if in == nil {
		return nil
	}
	out := new(InfinispanManagementInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanSpec) DeepCopyInto(out *InfinispanSpec) {
	*out = *in
	out.Connector = in.Connector
	out.Management = in.Management
	out.Container = in.Container
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanSpec.
func (in *InfinispanSpec) DeepCopy() *InfinispanSpec {
	if in == nil {
		return nil
	}
	out := new(InfinispanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfinispanStatus) DeepCopyInto(out *InfinispanStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfinispanStatus.
func (in *InfinispanStatus) DeepCopy() *InfinispanStatus {
	if in == nil {
		return nil
	}
	out := new(InfinispanStatus)
	in.DeepCopyInto(out)
	return out
}
