name: Add Operand

on:
  workflow_call:
    inputs:
      image:
        description: "The FQN of the Operand image"
        required: true
        type: string
      version:
        description: "The upstream-version of the Operand"
        type: string
      ref:
        description: "The git reference to checkout"
        required: false
        default: main
        type: string
      repository:
        description: "The git repository to checkout"
        required: false
        type: string

  workflow_dispatch:
    inputs:
      image:
        description: "The FQN of the Operand image"
        required: true
        type: string
      version:
        description: "The upstream-version of the Operand"
        type: string
      ref:
        description: "The git reference to checkout"
        required: false
        default: main
        type: string
      repository:
        description: "The git repository to checkout"
        required: false
        type: string

jobs:
  add-operand:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}

      - name: Determine Upstream Version
        id: set_version
        env:
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_IMAGE: ${{ inputs.image }}
        run: |
          if [[ -z "$INPUT_VERSION" ]]; then
            IMAGE="$INPUT_IMAGE"
            TAG=${IMAGE#*:}
            VERSION=${TAG%.Final}
          else
            VERSION="$INPUT_VERSION"
          fi
    
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Add Operand
        run: ./scripts/ci/add_operand.sh
        env:
          IMAGE: ${{ inputs.image }}
          VERSION: ${{ env.VERSION }}

      - name: Commit changes and push to repository
        run: |
          git config user.email "infinispan@infinispan.org"
          git config user.name "Infinispan"
          git add config/manager/manager.yaml documentation/asciidoc/topics/attributes/community-attributes.adoc documentation/asciidoc/topics/supported_operands/
          git commit -m "Add Operand ${{ env.VERSION }}"
          git push

      - name: Trigger next workflow if branch is 2.4.x and success
        if: >
          success() && github.ref_name == '2.4.x' && contains(steps.set_version.outputs.version, '.Final') &&
          (startsWith(steps.set_version.outputs.version, '15.0.') || startsWith(steps.set_version.outputs.version, '15.2.'))
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}
          repository: ${{ inputs.repository }}
          event-type: trigger-next-workflow
          client-payload: |
             {
               "ref": "${{ github.ref_name }}",
               "repository": "${{ inputs.repository }}"
             }

      - name: Trigger next workflow if branch is main and success
        if: success() && github.ref_name == 'main' && contains(steps.set_version.outputs.version, '.Final')
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}
          repository: ${{ inputs.repository }}
          event-type: trigger-next-workflow
          client-payload: |
             {
               "ref": "${{ github.ref_name }}",
               "repository": "${{ inputs.repository }}"
             }
