name: Image Release

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      ref:
        description: "The Operator branch/tag to checkout when creating the image."
        required: true
        default: "main"
      repository:
        description: "The git repository to checkout"
        required: false
        type: string


jobs:
  check_operand:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_operand.outputs.changed }}
      skip: ${{ steps.check_pr_status.outputs.skip }}

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "infinispan-qe-bot"
          git config --global user.email "q*@infinispan.org"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || 'main' }}
          repository: ${{ github.repository }}
          token: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}
          path: operator

      - name: Check if new operand added
        id: check_operand
        working-directory: operator
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last release tag: $LAST_TAG"
          ADDED=$(git diff $LAST_TAG HEAD -- config/manager/manager.yaml | grep '^+' | grep '"upstream-version"' || true)
          echo "Added operand:"
          echo "$ADDED"
          if [ -n "$ADDED" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check open PRs from forks repository
        id: check_pr_status
        env:
          GH_TOKEN: ${{ secrets.FORK_PAT }}
        run: |
          PR1=$(gh pr list \
            --repo infinispan-qe-bot/community-operators \
            --state open \
            --json number \
            --jq 'length')
          PR2=$(gh pr list \
            --repo infinispan-qe-bot/community-operators-prod \
            --state open \
            --json number \
            --jq 'length')
          echo "Repo infinispan-qe-bot/community-operators PR count: $PR1"
          echo "Repo infinispan-qe-bot/community-operators-prod  PR count: $PR2"
          if [ "$PR1" -gt 0 ] || [ "$PR2" -gt 0 ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi  


  release:
    needs: check_operand
    if: (needs.check_operand.outputs.changed == 'true' && needs.check_operand.outputs.skip != 'true') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "infinispan-qe-bot"
          git config --global user.email "q*@infinispan.org"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}
          repository: ${{ github.repository }}
          token: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}
          path: operator

      - name: Get the latest tag and bump the minor version
        working-directory: operator
        id: bump_tag
        run: |
          ./scripts/ci/bump_version.sh

      - name: Tag the release
        working-directory: operator
        env:
          TAG_NAME: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          git tag -a "$TAG_NAME" -m "Release Operator:: $TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:qemu-v9.2.0
          cache-image: false

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Quay
        uses: docker/login-action@v4
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: operator
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/infinispan/operator:${{ steps.bump_tag.outputs.new_tag }}
          build-args: |
            OPERATOR_VERSION=${{ steps.bump_tag.outputs.new_tag }}

      - name: Create OLM Bundle
        working-directory: operator
        run: |
          rm -rf bundle bundle.Dockerfile
          make bundle VERSION=${{ steps.bump_tag.outputs.new_tag }} CHANNELS=stable DEFAULT_CHANNEL=stable IMG=quay.io/infinispan/operator:${{ steps.bump_tag.outputs.new_tag }}

      - name: Checkout community-operators repo
        uses: actions/checkout@v6
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators
          ref: main

      - name: Copy contents of bundle/
        working-directory: community-operators
        run: |
          mkdir -p operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          cp -R ../operator/bundle/* operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          git add operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          git commit -s -m "Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}"

      - name: Create Pull Request to community-operators repo from forked repository
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.FORK_PAT }}
          path: community-operators
          commit-message: 'Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}'
          committer: infinispan-qe-bot <q*@infinispan.org>
          author: infinispan-qe-bot <q*@infinispan.org>
          branch: pr_request
          delete-branch: true
          push-to-fork: infinispan-qe-bot/community-operators
          title: 'Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}'
          body: 'Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}'

      - name: Checkout community-operators-prod repo
        uses: actions/checkout@v6
        with:
          repository: redhat-openshift-ecosystem/community-operators-prod
          path: community-operators-prod
          ref: main

      - name: Copy contents of bundle/ and issue PRs
        working-directory: community-operators-prod
        run: |
          mkdir -p operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          cp -R ../operator/bundle/* operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          cp ../operator/release-config.yaml operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          git add operators/infinispan/${{ steps.bump_tag.outputs.new_tag }}
          git commit -s -m "Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}"

      - name: Create Pull Request
        id: cpr1
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.FORK_PAT }}
          path: community-operators-prod
          commit-message: 'Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}'
          committer: infinispan-qe-bot <q*@infinispan.org>
          author: infinispan-qe-bot <q*@infinispan.org>
          branch: pr_request
          delete-branch: true
          push-to-fork: infinispan-qe-bot/community-operators-prod
          title: 'Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}'
          body: 'Operator Infinispan ${{ steps.bump_tag.outputs.new_tag }}'

      - name: Trigger Post Release job
        env:
          REF: "${{ github.ref_name }}"
          REL_VERSION: ${{ steps.bump_tag.outputs.new_tag }}
        uses: cardinalby/schedule-job-action@v1
        with:
          ghToken: ${{ secrets.INFINISPAN_RELEASE_TOKEN }}
          targetBranch: 'main'
          templateYmlFile: 'operator/.github-scheduled-workflows/publish-main.yaml'
          targetYmlFileName: publish-main.yaml
          copyEnvVariables: REF REL_VERSION

      - name: Update website release data
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: infinispan/infinispan.github.io
          event-type: release_updated
          client-payload: '{"project": "operator", "version": "${{ steps.bump_tag.outputs.new_tag }}"}'
