name: PR Needs Rebase

on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  rebase-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check PR conflicts and update label
        uses: eps1lon/actions-label-merge-conflict@0273be72a0bbd58fcd71d0d6c02c209b50d1e5e1 # v3
        with:
          dirtyLabel: "pr/needs rebase"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
