name: Synchronize documentation with Infinispan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        ref: main

    - name: Clone infinispan
      uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      with:
        repository: infinispan/infinispan
        ref: 14.0.x
        path: infinispan

    - name: Wipe the sync directory
      run: |
        cd documentation/asciidoc/topics/sync
        rm -rf *

    - name: Sync docs
      run: |
        rsync -vr --delete infinispan/documentation/src/main/asciidoc/topics/xml/cache_template_inheritance.xml ./documentation/asciidoc/topics/sync/xml/
        rsync -vr --delete infinispan/documentation/src/main/asciidoc/topics/yaml/cache_template_inheritance.yaml ./documentation/asciidoc/topics/sync/yaml/
        rsync -vr --delete infinispan/documentation/src/main/asciidoc/topics/json/cache_template_inheritance.json ./documentation/asciidoc/topics/sync/json/
        rm -rf infinispan

    - name: Commit files
      run: |
        git config --local user.email "infinispan@infinispan.org"
        git config --local user.name "Infinispan"
        git add . --all
        git diff-index --quiet HEAD || git commit -m "Synchronized config examples from Infinispan"

    - name: Push changes to develop
      uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: main
