name: Hot Rod Rolling Upgrade Tests

on:
  workflow_call:

permissions:
  contents: read

env:
  TESTING_LOG_DIR: ${{ github.workspace }}/test/reports

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Install Dependencies
        uses: ./.github/actions/dependencies

      - name: Cache Operand Images
        uses: ./.github/actions/operand-cache

      - name: Initialize Kubernetes Cluster
        uses: ./.github/actions/kind

      - name: Webhook Tests
        run: make webhook-test PARALLEL_COUNT=5

      - name: Inspect Cluster
        if: failure()
        uses: ./.github/actions/inspect
        with:
          artifactPrefix: "webhooks"

      - name: Test Logs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure()
        with:
          name: webhook-test-logs
          path: ${{ env.TESTING_LOG_DIR }}
